### ISSUE TITLE
Headings Offset not being applied

### ISSUE THREAD

**Issue by shelldandy** [tscanlin/tocbot#100]
😢 

Other than on the default-options.js i don't see it really being used of affecting the end logic, am I missing something?

**Comment by tscanlin** [comment]
Its used right here: https://github.com/tscanlin/tocbot/blob/a8c4e8f6944619772f26ccdb39809849c2b07f4a/src/js/build-html.js#L155

**Comment by shelldandy** [comment]
True dat, however I'm applying a headingsOffset say of 200 but the heading is still scrolled to the top of the window 🤔 

Or how should that number be used?

**Comment by shelldandy** [comment]
Or maybe there is no option for what I mean haha

What I mean is if I have a fixed menu when I click a link from the TOC it scrolls to the top of the window but it can't be seen since the menu is on top of the window, so ideally we can set some sort of offset for that smoothscroll final position.

(BTW I already have smoothscroll implemented on that site, but since tocbot overrides it that's why im in need to know how this could be achieved 😄 )

**Comment by tscanlin** [comment]
The readme has a section on how to cover fixed headers with css.

**Comment by shelldandy** [comment]
Yeah, but thats a fixed number, a fixed header might have different sizes on different breakpoints or if scrolled a certain amount of pxls etc 😢

**Comment by tscanlin** [comment]
Different breakpoints could still be handled with media queries in CSS.

**Comment by tscanlin** [comment]
Doing this in JS is not a great solution since the document won't scroll back to the proper part with the selected heading when a user refreshes the page.

**Comment by shelldandy** [comment]
But not all content has the id's already set in place, in some cases they need to be generated dynamically before using this plugin.

For example with wordpress or shopify generated content in which case if the user doesn't have any JS then it doesn't really matter since no TOC nor hashes would work 🤔

**Comment by shelldandy** [comment]
Hey man its ok I get it that there is no option to make that happen and that you think your opinions are the best and there are no edge cases.

I got it working in the end with just vanilla js 😛 so Im guessing this issue won't lead to anything done.

I could PR but it doesn't seem like you'd accept it since the idea goes against your opinion.

Cheers and thanks for the plugin anyways!

**Comment by tscanlin** [comment]
I never said any of those things, I’ve been trying to understand your problem(s) so that I can help you. Frankly I think you could learn to be a bit more appreciative when others try to help you.

**Comment by shelldandy** [comment]
My point was the CSS only is not the answer all the time, there are times when you need that autoscroll to be dynamic for several reasons:

- The header changes size depending of the breakpoint and scrolled amount.
- The rendered content doesn't have the required ids to begin with. So if a user refreshes the page that still wouldn't work because: ⬇️ 
- There is already a smooth scroll solution in place for links with hashes that the plugin overrides (for example not changing the `location.hash` so if the user refreshes well... nothing would happen because ⬆️ )

**Comment by tscanlin** [comment]
You could still dynamically change the css via js if it needs to be that dynamic. But thank you for outlining your usecase so well, that is very helpful for me. I recently got an email from another user who had a similar issue and made a solution that perhaps could be helpful to you, see: https://github.com/tscanlin/tocbot/pull/101

If you wouldn’t mind posting the code you came up with in this issue, maybe it will be helpful for me or other users.

Thanks!

**Comment by shelldandy** [comment]
> If you wouldn’t mind posting the code you came up with in this issue, maybe it will be helpful for me or other users.

Nothing that wasn't done here tbh just copied most of the source from here to generate the TOC without any logic for the smoothscroll since I had that setup already to consider those offsets.

So if anything the most helpful thing in those cases could be to not take over the click event entirely or let the users opt out so they can provide their own smooth scrolling logic with JS or CSS or a mixture of both.

**Comment by dbjpanda** [comment]
> True that, however I'm applying a headingsOffset say of 200 but the heading is still scrolled to the top of the window 🤔 Or how should that number be used?

@tscanlin I don't think that your answer "The readme has a section on how to cover fixed headers with css." replies this question. That is an alternative solution which is great. However I am asking it again. Please let us know if that option `headingsOffset` has any effect. Or the only solution is through css ?

**Comment by tscanlin** [comment]
CSS is the only solution that works well across browsers since back button support  doesn't work with JS. see: https://github.com/tscanlin/tocbot/issues/100#issuecomment-402553538

**Comment by dbjpanda** [comment]
@tscanlin So you mean `headingsOffset` works only in some particular browsers but not in all ?

**Comment by tscanlin** [comment]
That option is really just meant for minor adjustments due to rounding errors in the browser with determining which heading is highlighted. It's not intended for handing floating headers and such.
