### ISSUE TITLE
Please explain tocbot styles and layout

### ISSUE THREAD

**Issue by nareshbhatia** [tscanlin/tocbot#102]
@tscanlin, thank you for this great library - exactly what I need.

However struggling a bit with styling and layout. It's not clear to me how the supplied styles are intended to be used. I am simply looking for a left/right layout with toc on the left. Also there is a fixed header at the top. I tried using flexbox to create the left/right layout, but that's not quite working. Would you mind clarifying how I am supposed to use the styles in `tocbot.css`?

I have created a minimal project at https://github.com/nareshbhatia/tocbot-demo.

**Comment by tscanlin** [comment]
Glad to hear you like Tocbot!

Supplied styles should just be included on the page like any other CSS you have. In your demo it looks like you are importing it properly. But tocbot is unopinionated about styling for the rest of the page. Looks like you need to add styles for .toc and .content still to achieve the layout you want. Display: inline-block with widths that add up to 100% should work well.

For the fixed headers, see this section in the README:
https://github.com/tscanlin/tocbot#fixed-headers

**Comment by nareshbhatia** [comment]
Thanks, @tscanlin. I was able to fix all my issues with your guidance. All set now!
