### ISSUE TITLE
OL option not working

### ISSUE THREAD

**Issue by bgajus** [tscanlin/tocbot#105]
I am not having any luck getting the OL option to turn off when I set it to false. Not sure if it's something on my end or not. Can someone check to see if they are having the same issue?

**Comment by tscanlin** [comment]
Hmm, sounds like a strange issue.. Can you post some example code?

**Comment by tscanlin** [comment]
Make sure you are using the most recent version `4.4.0`

**Comment by tscanlin** [comment]
Were you able to figure this out @bgajus?

**Comment by bgajus** [comment]
Hey sorry for the delay. Yeah looks like I had been using 4.3.1. Fixed when I went to 4.4.0. Thanks!

**Comment by bgajus** [comment]
Hey @tscanlin does tocbot not create id attributes for the headings on the page automatically? Is that something I have to do manually? I have some pages with between 50-100 headings so adding those manually would be cumbersome. Thanks!!

**Comment by tscanlin** [comment]
Tocbot does not concern itself with modifying the source content so it does not add ids itself.

Are you using any sort of libraries on the server to render markdown or anything?

**Comment by tscanlin** [comment]
If there is absolutely no way to add the ids to the server rendered content then you can use this snippet before Tocbot init to add them. 

https://github.com/tscanlin/tocbot/blob/master/src/utils/make-ids.js

**Comment by bgajus** [comment]
Thanks so much for the snippet. I had to make one small change to it but it worked perfectly!

**Comment by tscanlin** [comment]
Glad to hear!
