### ISSUE TITLE
is-active-link error

### ISSUE THREAD

**Issue by jay38134** [tscanlin/tocbot#106]
when the content is very small, i click the  toc-link, the is-active-link is error. in my opinions, you should add active when you click and scroll, not only use click to trigger scroll

**Comment by tscanlin** [comment]
It should activate with click and scroll. Can you send a video or link me to an example?

Maybe the body isn’t scrollable? If you check out the demo site both should work.

**Comment by tscanlin** [comment]
you need enough bottom padding to b able to scroll to that element.
try adding this style to the content element: https://github.com/tscanlin/tocbot/blob/master/src/scss/_page-styles.scss#L30

**Comment by jay38134** [comment]
> you need enough bottom padding to b able to scroll to that element.
> try adding this style to the content element: https://github.com/tscanlin/tocbot/blob/master/src/scss/_page-styles.scss#L30

if i use this css style, my website will be much blank, this will make the website ugly, this is not a good idea

**Comment by tscanlin** [comment]
The active item in the toc only highlights when the heading is at the top of the browser window so this is by design. If you’d like to propose an alternative solution please open a pull request.

**Comment by jay38134** [comment]
> The active item in the toc only highlights when the heading is at the top of the browser window so this is by design. If you’d like to propose an alternative solution please open a pull request.

thank you for your reply, i close this issue
