### ISSUE TITLE
smooth scrolling prevent browser history

### ISSUE THREAD

**Issue by yanns** [tscanlin/tocbot#107]
First thanks a lot for this very useful library! 😍 

When the smooth scrolling is enabled, the browser location is not updated when we click on one link.

The browser history is prevented. It's not possible to use back and forth navigation anymore.

**Comment by tscanlin** [comment]
What version are you using? I know the latest, `4.4.0` shouldn't prevent default with smooth scroll.
see: https://github.com/tscanlin/tocbot/blob/82f28286b46521a3a876bee771bc603d5d67b625/src/js/scroll-smooth/index.js#L30

Let me know if upgrading fixes this.

**Comment by tscanlin** [comment]
I'm updating the readme: https://github.com/tscanlin/tocbot/pull/108

**Comment by yanns** [comment]
I confirm it's working with the last version. Thx a lot! ❤️
