### ISSUE TITLE
Indexing table rows

### ISSUE THREAD

**Issue by nicoulaj** [tscanlin/tocbot#109]
I would like to have rows for a long table appear in the TOC, so I put a header in one cell per row. It mostly works, the TOC displays as expected, but there is a bug where only the last row is always marked as active.

Here is a reproducer: https://jsfiddle.net/nicoulaj/vwr52eoq/2/

Not sure if there is a better way to do this ?

**Comment by tscanlin** [comment]
The tables mess up the way element offsets are calculated so the correct link isn't being highlighted. Unfortunately a fix for this isn't very straightforward. However your layout seems simple enough that you could accomplish the same with some div's. Can you try that?

**Comment by nicoulaj** [comment]
That was a simplified example just for the bug, I actually need to use real tables. I guess I'll just turn off the active link indicator in this case.

**Comment by tscanlin** [comment]
This is the first time that this has come up. Out of curiosity, why do you need to use real tables?

**Comment by nicoulaj** [comment]
Mostly because I use [datatables](https://datatables.net) to make them sortable, hide/show columns, and it only supports standard tables as far I know.
