### ISSUE TITLE
请问能否使用bootstrap的theme？

### ISSUE THREAD

**Issue by ztmsimon** [tscanlin/tocbot#11]
请问能否使用bootstrap的theme？
高亮的颜色能否调节？

**Comment by tscanlin** [comment]
I'm not sure what you are asking because I do not understand chinese. When I translate what you typed I see:
"Will the ability to use the bootstrap theme?
Highlight color Regulate ?"

This project does not require bootstrap if that's what you are asking.

**Comment by tscanlin** [comment]
If you check the releases page there are compiled files:
https://github.com/tscanlin/tocbot/releases

**Comment by ztmsimon** [comment]
i'm very gald your answer.
translate is fine
your project is very good.but i'm a freshman in html,can you description how to use it step by step?
for example,should i write anyhing in html,etc <div>...?

**Comment by tscanlin** [comment]
Sure! I am happy to help.

First download the files from here:
https://github.com/tscanlin/tocbot/releases/

Then include the css in the head of your HTML document:
<link rel="stylesheet" href="assets/css/tocbot.css">

And include js at the bottom before the closing </body> tag:
<script src="assets/js/tocbot.js"></script>

Then in the body tag have:
'''
<div class="js-toc"></div>
<div class="js-toc-content">
<h1 id="heading-1">Heading 1</h1>
<p>some text</p>
<h2 id="heading-2">Heading 2</h2>
</div>
'''

And that should work. Just make sure the css/ js is somewhere relative to your HTML file. Hope that helps!

**Comment by tscanlin** [comment]
Did that help answer your question or are you still stuck??
