### ISSUE TITLE
heading.offsetTop always equals 0

### ISSUE THREAD

**Issue by robiningelbrecht** [tscanlin/tocbot#111]
So I've implemented TocBot (thanks for the great library btw!) on my website, but the last link in the toc is always the active one.
I've started to debug this and seems 

`heading.offsetTop `

in 
```
if (heading.offsetTop > top + options.headingsOffset + 10) {
}
```
always equals 0, for all links.

So TocBot just sets the last one as the active one... I can't blame him ;)

Any idea why heading.offsetTop is always zero?
When I'm using `jQuery('my-selector').offset().top`, the offset is calculated. But from my understanding jQuery calculates this using the document selector and javascript using the parent node?

UPDATE:
I briefly changed `heading.offsetTop` to `heading.getBoundingClientRect().top` and this seems to fix the problem as this calculates the offset using the document/view port...

**Comment by tscanlin** [comment]
Oh thanks for the heads up about this? Are you using tables for your content btw? great investigative work looking into `getBoundingClientRect`, thank you!

**Comment by tscanlin** [comment]
Sorry for my delay in responding. I've been away on vacation. Are you using tables by chance?

**Comment by dbjpanda** [comment]
I am too facing the same issue.  Though I haven't investigated. I am referring #53 and #100 . I am using tocBot with Jquery. However the  `headingsOffset` doesn't seems have any effect whatever value I set. Can you please give us an working example how to use that option ?

**Comment by tscanlin** [comment]
Can you link me to an example in a new issue @dbjpanda?
