### ISSUE TITLE
Failed to build table of content for headers in separate cells in Jupyter notebook

### ISSUE THREAD

**Issue by BoPeng** [tscanlin/tocbot#116]
I am testing tocbot and check if it can be used to replace tocify.jquery. I notice that it cannot build TOC for documentations where headers are arranged like

```
<div class=cell>
<h2>... </h2>
</div>
<div class=cell>
<h3>...</h3>
</div>
```
because `h3` is not a child of `h2`.  An example for such a document is at https://vatlab.github.io/sos-docs/doc/examples/RNASeqGTEx_report.html where a [modified version of tocify.jquery](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/assets/jquery.tocify.js#L243) was used to generate the toc.

Does this look like a valid use case for tocbot? Will tocbot be able to support it?

**Comment by tscanlin** [comment]
You are missing ids for your headings so I think that’s why it’s not working properly. Can you try adding those to see if it fixes it? If you can’t generate them on the server side I have linked to a script in previous issues that can generate them. Hopefully that helps!

Note, I’m currently on vacation in south east Asia so my apologies if I’m slow to respond. Hope the start of 2019 is going well for you!

**Comment by BoPeng** [comment]
No. The links have IDs. If you check the source of https://vatlab.github.io/sos-docs/doc/examples/RNASeqGTEx_report.html, you will see the headings are like

```
<div class="inner_cell">
 <div class="text_cell_render border-box-sizing rendered_html">
 <h3 id="Quantile-normalization">Quantile normalization
<a class="anchor-link" href="#Quantile-normalization"></a></h3>
<p>Quantile normalization of RNA-seq data</p>
 <ol>
```

**Comment by tscanlin** [comment]
I'm back from my trip. From the looks of your page tocbot should work just fine with it.

If you are having any specific issues can you post an example so that I can take a look? Thanks.

**Comment by BoPeng** [comment]
Thanks. I tried again but made it work. The default css has a lot to be desired compared to tocify though. I think this is because tocify used bootstrap `nav` for the lists and tocbot does not.

But anyway I think this ticket should be close. I will open another ticket if I notice any problem.
