### ISSUE TITLE
Vertical bar extending far beyond the list enteries using BS4. 

### ISSUE THREAD

**Issue by egkareem** [tscanlin/tocbot#117]
Thank you this add-on. 

I have an issue/question. Please check this jsFiddle:
https://jsfiddle.net/ekareem/19rybof5/21/ 
Question 1:
In there you can see that a white vertical bar that significantly extends beyond the list items.
I think the bar should be as long as the vertical content only, for example as the case is in your web site.
Is there any way I could customize the width or the length of this bar?

Question 2:
I want to be able to some how make the last clicked (current) link stand out either by color, background color or margin settings. How can this be accomplished? 

Thanks much.

Thank you.
Edit: 
I have received an answer for this, I am keeping this question in case someone else could benefit. Feel free to either answer it, consider it closed or delete it altogether.

https://stackoverflow.com/questions/54202804/how-to-properly-set-tocbot-with-bootrap-4/54209746#54209746

**Comment by tscanlin** [comment]
For 1, you can use `overflow-y: hidden on the toc container to keep the line from extending far down the page.

For 2, If you add adequate space that the bottom for the user to scroll to that heading the last one can show. For instance add `padding-bottom: 80vh;` to your content container.

**Comment by egkareem** [comment]
Thank you for your help. Adding body{overflow-y: hidden;} did not make a change for issue 1. I tried this on the jsfiddle above.

**Comment by tscanlin** [comment]
Actually just add `js-toc toc` you missed the toc class and that seemed to mess up the css

**Comment by egkareem** [comment]
It is true that adding "toc" solves issue #1. However, this works correct for a list that is not numbered. So, the following line results in a list without the sequence number on the left and draws the vertical line correctly.

  ` <div class="js-toc orderedList toc"> </div>`

**Comment by tscanlin** [comment]
you can override `list-style: none` to get the list styling that you want.

**Comment by egkareem** [comment]
Thank you for your follow-up. You are correct this works:
.```
toc>.toc-list li{
    list-style:decimal-leading-zero !important;
}
I was under the impression that the parameter orderedList does that.
Thanks much.

**Comment by tscanlin** [comment]
That option just changes the element but doesn’t change styling. Sorry for the confusion!

**Comment by egkareem** [comment]
Thanks much for the clarification. I think the issue could be closed.
