### ISSUE TITLE
Headers without ID mess up with page scrolling

### ISSUE THREAD

**Issue by BoPeng** [tscanlin/tocbot#118]
I am trying to use tocbot for my tocify-based TOC for my documentations. To make things look as close as possible to the old version, I did a drop-in replacement in my template [here](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561). That is to say,

1. I [kept tocify.css](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25L4) and [added tocbot.css after it](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25R6).

2. I [remove jquery, jquery-ui, tocify](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25L38), and [added tocbot](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25R38)

3. I replaced [tocify init function](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25L49) with [tocbot one](https://github.com/vatlab/sos-notebook/commit/859da09bf34e5d21759869978244e4f34273e561#diff-7cf04d636759ec6a27c620bc2d4f2a25R41) but I used all the tocify class names so that I can continue to use the tocify css.

I used the new template and generated 

https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook_tocbot.html

with its tocify version 

https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html

Now, when I scroll down the page, I notice multiple items are highlighted

![image](https://user-images.githubusercontent.com/9889312/51422902-eac22f00-1b7c-11e9-95be-8631d11e3e3c.png)

Is this a bug or something wrong with my configuration? Note that the blue bar comes from

```
li.tocify-item.active {
  background-color: #6197d5;
}
```

with class names specified by

```
    listItemClass: 'tocify-item',
    activeListItemClass: 'active',
```

**Comment by BoPeng** [comment]
Thanks for your quick response. I have 

```diff
--- a/doc/user_guide/sos_in_notebook_tocbot.html
+++ b/doc/user_guide/sos_in_notebook_tocbot.html
@@ -12505,10 +12505,8 @@ textarea.sos-source {
 #notebook-container {
   box-shadow: none;
 }
-li.tocify-item.active {
+li.tocify-item .is-active-link {
   background-color: #6197d5;
-}
-.tocify-item.active a {
   color: white;
 }
```
tried to highlight the link instead of item (which can be the whole sublist if I understand correctly), but I notice something weird for the highlight of items. That is to say, when I scroll down the page of 

http://localhost:8000/doc/user_guide/sos_in_notebook_tocbot.html

Highlighted item would  jump back and forth and never leave "SoS is extended from 3.6". My understanding is that `.is-active-link` stays at the parent level. How can I fix this behavior? Note that I have tried to remove tocify css and the pure tocbot version has the same problem.

**Comment by BoPeng** [comment]
I noticed that the problem goes away if I limit the headers to `h2, h3`, so the problem seems to be with the structure of

```
<h2>
<h4>
<h2>
...
```
namely the skipping of `h3` in some places of the document.

**Comment by BoPeng** [comment]
OK, The real issue is that these `<h4>` are headers inside the bootstrap warning boxes and do not have IDs.

**Comment by BoPeng** [comment]
@tscanlin Tocify solves this problem by adding a [`data-unique` field to the headers](https://github.com/gfranko/jquery.tocify.js/blob/c179865a65c86e9323cdf2b9bfc66f812f077079/src/javascripts/jquery.tocify.js#L386), do you think tocbot can do the same?

**Comment by BoPeng** [comment]
Another option is to simply ignore headers without `id`, not ideal but at least makes scrolling appear normal.

**Comment by tscanlin** [comment]
I have made a script to do this on the client side, try using this:
https://github.com/tscanlin/tocbot/blob/master/src/utils/make-ids.js

Based on your feedback I've updated the readme to include a link to this. I've hesitated in the past because generating id's on the client-side is not ideal because they aren't reliable / fast enough to always take the user down to the same spot on the page (with the generated url hashes) in my experience. The ID's need to come from the server for the browsers native scroll positioning behavior to work properly. Anyway hopefully this solution is adequate for you and addresses your issue.

**Comment by BoPeng** [comment]
I have never experienced any performance issues or problem related to uniqueness url hashes, but perhaps you are right that generating IDs should be the responsibility of client/users. However, if TOC items with missing IDs cannot point back to the headers, what it the point of including them in the TOC? It would be much cleaner to remove headers without IDs even headers with duplicated IDs so that the generated TOCs work properly.

**Comment by tscanlin** [comment]
you should just be able to do that in the selector then `headingSelector: 'h1[id], h2[id], h3[id]',`
