### ISSUE TITLE
TOC does not expand on click for short documents.

### ISSUE THREAD

**Issue by BoPeng** [tscanlin/tocbot#123]
[demo.html.txt](https://github.com/tscanlin/tocbot/files/2789774/demo.html.txt)

With the attached HTML page with TOC generated by tocbot (please remove .txt extension), I noticed that

1. If the browser window is tall and everything fits in one window, clicking on Usage does not expand the subheaders.
2. If the browser is shorter, scrolling and clicking would work normally.

Is this a bug?

**Comment by tscanlin** [comment]
This is not a bug. The links for the headings only highlight when they reach the top of the viewport. If your page isn't long enough you need to add sufficient padding on the bottom for those headings to be scrolled to. Something like `padding-bottom: 90vh`

**Comment by BoPeng** [comment]
I was not talking about scrolling, I expected the heading to expand because there are subheaders.
