### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by BoPeng** [tscanlin/tocbot#124]
1. Visit https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html
2. Turn on inspector
3. Click: "Execute embedded workflows using magic %sosrun" or any link with '%'

An error message appears:

```
tocbot.min.js:1 Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
    at o (tocbot.min.js:1)
    at HTMLBodyElement.n (tocbot.min.js:1)
```

**Comment by tscanlin** [comment]
Can you avoid using that character in your titles?

**Comment by BoPeng** [comment]
Is the ID valid? If so, tocbot should create a proper URL to point to it, right?

**Comment by tscanlin** [comment]
It may be valid for an id now in html5 but it isn't allowed in url's without proper encoding which is why its best to avoid. I updated the make-ids script to handle more special characters and made a patch release. See: https://github.com/tscanlin/tocbot/blob/master/src/utils/make-ids.js

**Comment by BoPeng** [comment]
"a solution" is easy to come up but I do not understand your resistance to allow tocbot to work with more documents. As you can see from the number of tickets I created, I have had a lot of trouble in using tocbot and none of them happened with `tocify.js`.
