### ISSUE TITLE
'is-active-link' does not change while scrolling

### ISSUE THREAD

**Issue by mashirozx** [tscanlin/tocbot#126]
![image](https://user-images.githubusercontent.com/16148054/52175428-9f478c00-27de-11e9-9a52-e583d5b82f01.png)

In my condition, `html` and `body` were set to be `overflow:hidden`, and the article content is scrolling inside a fixed container, whose position was fixed by [Flexbox Layout](https://www.w3schools.com/css/css3_flexbox.asp). The initial script here:

```js
tocbot.init({
	// Where to render the table of contents.
	tocSelector: '.toc',
	// Where to grab the headings to build the table of contents.
	contentSelector: '.entry-content article',
	// Which headings to grab inside of the contentSelector element.
	headingSelector: 'h1, h2, h3, h4, h5',
});
```

The page with promblem [here](https://mashiro.top/Gorgeous/page.html).

**Comment by mashirozx** [comment]
Tried to fix it, now it can change between toc items. But they won't change while scrolling, they only change when click on page... You can see at my page:flushed:
I really don't no how to fix it completely...

**Comment by mashirozx** [comment]
Seems some error info in console... But I'm not familiar with Nodejs, don't know how to debug...
![image](https://user-images.githubusercontent.com/16148054/52187696-eaf34780-2869-11e9-9e5f-3e6282c4b2e6.png)

**Comment by mashirozx** [comment]
> Seems some error info in console... but the tocbot still works.
> I'm not familiar with Nodejs, don't know how to debug...
> ![image](https://user-images.githubusercontent.com/16148054/52187696-eaf34780-2869-11e9-9e5f-3e6282c4b2e6.png)

Tried to fix in [this way](https://github.com/mashirozx/tocbot/commit/4068bc07f7c7fe073f08d1555fd5fdac1e408ecf), not sure whether it's a good idea.

**Comment by tscanlin** [comment]
Having a non-scrolling html / body won't work well with anchor tags. For instance when loading `https://mashiro.top/Gorgeous/page.html#mashiro-3` it may work well in chrome but it breaks in safari and doesn't take you to the proper part of the page on load. I have a section of the readme that talks about how to handle fixed headers and even works without js, see here: https://github.com/tscanlin/tocbot#fixed-headers

Hope that helps!

**Comment by mashirozx** [comment]
Maybe my expression is not clear, not native English speaker :)

Here are two demos, [demo 1](https://pages.shino.cc/toc%20demo/demo1.html) includes original `tocbot.4.3.1.min.js`, and [demo 2](https://pages.shino.cc/toc%20demo/demo2.html) includes my fix `tocbot.fix.min.js` @ PR #129. You may download demo's source code [here](https://pages.shino.cc/toc%20demo.zip).

As you said `https://mashiro.top/Gorgeous/page.html#mashiro-3` not work, the reason is the `<h>` tags' `id`s was generated by JavaScript, there is no `id` when the page load, so it won't jump in any browser. 🙃

**Comment by mashirozx** [comment]
Actually the site <https://mashiro.top/Gorgeous/> I'm working on has a horizontal layout, maybe there be much better layout methods, but in the current site framework, the `overflow: hidden` is necessary (`body`'s vertical scroll is not allowed). Also, I think a `scroll container` option as the PR could be useful in both mine and many other conditions.

**Comment by tscanlin** [comment]
Since its not too much code and it serves your use case I'm ok adding it. Thanks for the PR!

I left some feedback on your PR. Once you address that I can merge.

**Comment by indrajittiwari** [comment]
> Maybe my expression is not clear, not native English speaker :)
> 
> Here are two demos, [demo 1](https://pages.shino.cc/toc%20demo/demo1.html) includes original `tocbot.4.3.1.min.js`, and [demo 2](https://pages.shino.cc/toc%20demo/demo2.html) includes my fix `tocbot.fix.min.js` @ PR #129. You may download demo's source code [here](https://pages.shino.cc/toc%20demo.zip).
> 
> As you said `https://mashiro.top/Gorgeous/page.html#mashiro-3` not work, the reason is the `<h>` tags' `id`s was generated by JavaScript, there is no `id` when the page load, so it won't jump in any browser.

Thanks..Its working for me
