### ISSUE TITLE
Left border extends way further down than expected

### ISSUE THREAD

**Issue by devth** [tscanlin/tocbot#130]
Any ideas why the border hangs down so far?

![image](https://user-images.githubusercontent.com/86107/53307823-7ce2e480-3859-11e9-9153-240ed7a0b86b.png)

Repro visible at https://yetibot.com/dev-guide#data_across_pipes

**Comment by tscanlin** [comment]
you just need to add `overflow: hidden` to the wrapper of all of the items.

**Comment by devth** [comment]
That fixed it. Thanks!!

**Comment by nfabredev** [comment]
I also needed to add `position: relative` to that element as the `.toc-link:before` element has an absolute position.

```css
.js-toc {
  position: relative;
  overflow: hidden
}
```
