### ISSUE TITLE
Optional hashing function?

### ISSUE THREAD

**Issue by tkeffer** [tscanlin/tocbot#134]
Tocbot requires that every heading have a unique id. For a long document, that can be a laborious chore.

One of the nice features of tocify is that one can specify an optional [`hashGenerator`](http://gregfranko.com/jquery.tocify.js/#Options) function. Input is the text of the header, output is the id. This way, there is no need to go through the document, creating ids. 

Any plans to add something like this?

**Comment by tkeffer** [comment]
Never mind. Figured out how to do what I need using `make-ids`.

**Comment by tscanlin** [comment]
Thank you for reading the readme :)

**Comment by bymayo** [comment]
Anyone coming to this, I couldn't find anything about this in the README, but it's in the `src/utils` folder:

https://github.com/tscanlin/tocbot/blob/master/src/utils/make-ids.js

**Comment by tscanlin** [comment]
Thanks for calling this out here @bymayo, the more places it's mentioned the better. :)

I do mention it in the readme when I say: "Make sure rendered headings have id attributes, some markdown libraries (like marked) already do this. If you need to do this client side see this script."
"this script" links to it but maybe that should be more obvious. Anyway, I appreciate the feedback and the time you took to leave a comment. 👍

**Comment by bymayo** [comment]
@tscanlin I see it now! Might be worth adding a Utils heading or something.

Nice work though, the plugin works great!
