### ISSUE TITLE
Highlighting titles within nested relative positioned containers

### ISSUE THREAD

**Issue by geomaedr** [tscanlin/tocbot#135]
Hi @tscanlin! 

first of all, i really like tocbot!

However, i ran into a challenge with having headings nested in relative positioned containers inside the contentSelector, which prevents the correct highlighting of those headings in the toc while scrolling.
This is related to the usage of `offsetTop` which returns the top position to the next relatively positioned parent, whereas i would need something like `el.getBoundingClientRect().top`.
Maybe this is a considerable option to add? :)

Thanks and cheers,
Markus

**Comment by tscanlin** [comment]
Sorry for my delay in responding. I think your use case makes sense. Do you have time to implement this feature? If not, can you clarify more about how many nested containers you have and if a number or element makes sense for this option? I think the tricky thing is making this work well natively in the browser with back/ forward, refresh etc.. but if it can work well we should add this feature. Let me know.

**Comment by geomaedr** [comment]
Hi @tscanlin!
i did a pull request with a suggestion: https://github.com/tscanlin/tocbot/pull/136
It still makes use of `offsetTop` and shouldn't interfere with the browsers back/forward/refresh
