### ISSUE TITLE
Skipping headings being highlighted on scroll

### ISSUE THREAD

**Issue by digehode** [tscanlin/tocbot#139]
I can't see any reason for this behaviour. I've checked the HTML with a number of tools, made sure everything has an ID and still get strange behaviour.  The highlighted heading in the ToC works for the first few in my document, then selects the final one from about half way through, even though there are other headings that are shown in the ToC and visible on the page.  My guess is that it is something to do with the layout DIVs but it's hard to know for sure.

I made a static version of an example page, which demonstrates the behaviour: [https://codepen.io/digehode/pen/armYwX](https://codepen.io/digehode/pen/armYwX)

I fully expect someone to point out that I've been dumb, but I promise I've tried to rule that out first!

**Comment by tscanlin** [comment]
Try removing the use of flexbox for the layout. Doing a two column layout you really don't need it and it messes up the way offsets are calculated by the browser. Try removing / commenting out boostrap css, without that you should see the normal behavior.
