### ISSUE TITLE
Is there any option for numbering list items like 1.1, 1.1.2 ? 

### ISSUE THREAD

**Issue by dbjpanda** [tscanlin/tocbot#143]
Is there any option fur numbering the list items E.g . If not can it be taken as a feature request ? 
```
1. Heading 1
  1.1 Sub heading 1
  1.2 Sub heading 2
2. Heading 2
```

**Comment by tscanlin** [comment]
This can be done with CSS.

**Comment by JeroenSteen** [comment]
How can this be done with CSS? I understand the numbers are shown at the ::marker selector.

**Comment by tscanlin** [comment]
Yeah, you need to use counters in CSS, see this article for more info:
https://www.smashingmagazine.com/2019/07/css-lists-markers-counters/#counters

**Comment by ibarapascal** [comment]
To give a direct example when you are using TailwindCSS,

without touching the classes you can directly add:

- global.css

```css
@layer utilities {
  ::marker {
    content: counters(list-item,'.') '.';
  }
}
```

<img width="271" alt="Screenshot 2023-12-18 at 17 11 19" src="https://github.com/tscanlin/tocbot/assets/30466424/acd82d53-db82-47ae-829e-d5c2c615065d">
