### ISSUE TITLE
Style of last element breaks

### ISSUE THREAD

**Issue by sowinski** [tscanlin/tocbot#146]
Hi,

any idea why the line at the last element is to long?
I build an example here: http://jsfiddle.net/2xkbpezn/3/

![Bootstrap grid examples - JSFiddle - Google Chrome_077](https://user-images.githubusercontent.com/1528746/62366072-2c696480-b526-11e9-9a1e-18f4eca5454e.png)

(I copied the css from the npm package)

Thank you :)

**Comment by tscanlin** [comment]
Please see my answer in this previous issue:
https://github.com/tscanlin/tocbot/issues/117#issuecomment-455735446
