### ISSUE TITLE
Error when loading in browserify bundle

### ISSUE THREAD

**Issue by tomyam1** [tscanlin/tocbot#153]
When loading the `tocbot` module to a `browserify` bundle, the following error is thrown:

```
Uncaught TypeError: Cannot read property 'document' of undefined
```
From that line:
https://github.com/tscanlin/tocbot/blob/c33debb117b41c5edcf661da83dd408117811f32/src/js/index.js#L41

From debugging I see that `root` is defined.

Seems to be an issue with the UMD wrapper.

Fixed it locally by doing:

```js
window.global = window;
require('tocbot');
delete window.global;
```

**Comment by tscanlin** [comment]
root is defined or undefined? what's it's value?

**Comment by tscanlin** [comment]
hopefully this fixes it:
https://github.com/tscanlin/tocbot/pull/155

**Comment by tscanlin** [comment]
can you try that out?

**Comment by tomyam1** [comment]
Nope.
the issue is that 
>  From debugging I see that root is defined.

**Comment by tomyam1** [comment]
You will get an error at
https://github.com/tscanlin/tocbot/blob/84fed16270b56c01766feb77ce67d7d25209814e/src/js/index.js#L213

**Comment by tscanlin** [comment]
good point, this update should handle that: https://github.com/tscanlin/tocbot/pull/155
