### ISSUE TITLE
HeadingsOffset is not working

### ISSUE THREAD

**Issue by Arifursdev** [tscanlin/tocbot#156]
Please fix it.

**Comment by tscanlin** [comment]
Can you provide more detail and a link or a screenshot?

**Comment by Arifursdev** [comment]
please i have tried this js plugin.to scroll to link with little bit offset.so i did HeadingOffset: 60 its not working.you can test it yourself.thanks

**Comment by tscanlin** [comment]
I think you misunderstand what that option does. Do you have a fixed header on your page?

**Comment by tscanlin** [comment]
Please respond back with a reproduction of you issue if you still want help, also have a look at the README.
