### ISSUE TITLE
TypeScript error on onClick method

### ISSUE THREAD

**Issue by dimakrsna** [tscanlin/tocbot#159]
Hello!
I want to thank you for a good and simple plugin with clear documentation. When using with TypeScript, I had an error in the onClick method. Expected is boolean type but method it is a function.

**Comment by tscanlin** [comment]
Thanks for pointing this out. I made a PR that should fix this. See #160

**Comment by tscanlin** [comment]
`4.9.1` is published with this fix. Thanks for reporting the issue @dimakrsna!
