### ISSUE TITLE
add css and min.js to repo 

### ISSUE THREAD

**Issue by maruilian11** [tscanlin/tocbot#16]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding `tocbot.css` and `tocbot.min.js` to git repo or nam package so that we can use **git auto-update config** or **npm auto-update config** to automatically add them and later version.
we will respect you if you don't want to do that, then we may add them manually with a PR, but it will be hard to keep your lib the latest version on cdnjs.
thank you very mush!

https://github.com/cdnjs/cdnjs/issues/8844

**Comment by tscanlin** [comment]
Yeah, I'd be happy to do this. Is it pretty typical that most people will just include them in a /dist folder or something? Also, does it need to be on the master branch? I do include those files on the gh-pages branch (see: https://github.com/tscanlin/tocbot/tree/gh-pages/assets) and they get automatically updated there on merges into master. Let me know if that's ok or if I need to include them in the master branch.

Also, I'm going to be out of town for the next 8 days with no internet access, so apologies in advance if I don't respond. But I can pick this up once I'm back on Sept 4th.

**Comment by maruilian11** [comment]
hi @tscanlin,
yes. most people put them in a `dist` folder, which is also we recommended.
If you have time to do that, I can wait, then send a PR to add your lib.
Or you want to keep the structure, I will send the PR asap because I didn't find out your files put on `gh-pages` branch. sorry... (It does't need to be on the master branch.)

**Comment by tscanlin** [comment]
The files you want are here:
https://github.com/tscanlin/tocbot/blob/gh-pages/assets/js/tocbot.min.js
and 
https://github.com/tscanlin/tocbot/blob/gh-pages/assets/css/tocbot.css

Raw files:
https://raw.githubusercontent.com/tscanlin/tocbot/gh-pages/assets/js/tocbot.min.js
and
https://raw.githubusercontent.com/tscanlin/tocbot/gh-pages/assets/css/tocbot.css

Let me know if that will work.

**Comment by maruilian11** [comment]
hi @tscanlin ,
is there only v2.1.4 on `gh-pages` branch?
can I get old version files?

**Comment by tscanlin** [comment]
Yes, only 2.1.4 is on the gh-pages branch. Old versions of the files are available for download on the releases page: https://github.com/tscanlin/tocbot/releases

**Comment by maruilian11** [comment]
thanks, so when 2.1.5 release, 2.1.4 will disappear from `gh-pages` branch, too?

**Comment by tscanlin** [comment]
Yes. is that going to cause problems?

**Comment by Piicksarn** [comment]
Hi @tscanlin 😀 
It always keep the same files and structure of library as which in **`gh-pages`** for each tags' content, so that we could use git repo url and tags to get files(which user needed) automatically.

**Comment by tscanlin** [comment]
I updated the package.json file as your docs indicated and I added the dist files. Let me know if there is anything else you need me to do.

https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

https://github.com/tscanlin/tocbot/tree/master/dist

**Comment by maruilian11** [comment]
thank you! now we are going to set dist as basepath of git auto-update config, all you need is replace the file in dist when new version release, and please keep the files of the tag commit matching its version so that your files on cdnjs will always be the latest version.
thanks for your cooperation!

**Comment by maruilian11** [comment]
hi @tscanlin, is it possible you can put dist to npm package in later versions? I think it's more convenient for you. We can use npm auto-update config rather than git. If you agree, I will send a PR to add current version, and when you put dist to npm package, you can open an issue in cdnjs repo or just ping us, let us know you put it, we will add npm auto-update config for it, which will make your lib always the latest version on cdnjs.

**Comment by tscanlin** [comment]
I'd rather not update old tags to add the dist folders. I want to avoid changing the git history and I don't think there is much value in adding old versions since everyone using cdnjs should be using the current version.

I added to the package.json for the npm auto update config already. https://github.com/tscanlin/tocbot/blob/master/package.json

Let me know if there is anything else I need to do.

**Comment by maruilian11** [comment]
I have sent a PR to add your lib [here](https://github.com/cdnjs/cdnjs/pull/8998), if there is anything wrong, please tell me. thanks for your cooperation!

**Comment by tscanlin** [comment]
Awesome, thank you!

I'm gonna close this issue out but feel free to comment here if you need anything else.

**Comment by maruilian11** [comment]
thanks!
because we usually set auto-update config for folder existing, may I ask is it possible you release a new version recently? (we hope to make sure `dist` folder exists.)
If it's not convenient for you, we can understand and add the config now.

**Comment by tscanlin** [comment]
I don't have any changes to be able to release a new version right now, but I updated the deploy script to automate the process of updating the dist folder so it will be updated whenever future versions are released. Hope that's ok.

**Comment by maruilian11** [comment]
ok~ I will report to our manager. 
If we need help, I will let you know.
thank you!
