### ISSUE TITLE
customize parser getHeadingLevel() to support different nesting then based on H tags

### ISSUE THREAD

**Issue by k2s** [tscanlin/tocbot#163]
for example for `headingSelector: 'h1, div.l2'` I would like to handle `div.l2` nested under h1, like it would be h2

**Comment by k2s** [comment]
I came also accross the need to build the label based on some node attributes (`data-label-for-toc`).

The `parser-content.js` calls `headingLabelCallback(text)` if provided in options to customize the text.
My suggestion is to add option `headingInfoCallback(text, level, node)` that could return:
* label
* level
* attributes to add to TOC `a` tag

**Comment by tscanlin** [comment]
What your use case or reason for wanting to change the heading level in the toc?

**Comment by k2s** [comment]
My reasons:
* I have content that is generated out of my control and it doesn't use only H tags for levels (it uses h1, div.l2, div.l3)
* there is `data-` property that contains shortened title that is suitable for TOC (the `headingLabelCallback()` is currently only good to cut long text)
* also the numbering is not part of text and it is also not left on renderer to decide the numbering - the numbering is part of ID and is stylled with CSS3 `::before { content: attr(id); }`

This is 3 lines modification that works for me and that adds `headingInfoCallback()` to options:

```js
  function getHeadingObject (heading) {
    var obj = {
      id: heading.id,
      children: [],
      nodeName: heading.nodeName,
      headingLevel: getHeadingLevel(heading),
      textContent: options.headingLabelCallback ? String(options.headingLabelCallback(heading.textContent)) : heading.textContent.trim()
    }

    if (options.includeHtml) {
      obj.childNodes = heading.childNodes
    }

    if (options.headingObjectCallback && heading.nodeType) {
      options.headingObjectCallback(obj, heading)
    }

    return obj
  }
```

Then I can use it like:

```js
tocbot.init({
  // ....
  headingObjectCallback: function (obj, node) {
    if (node.nodeName === 'DIV') {
      obj.textContent = obj.id + ' ' + obj.textContent
      obj.headingLevel = 2
      obj.nodeName = 'H2' 
    }
    console.log({...obj, node})
  }
})
```

I am wondering why the `getHeadingObject()` is called multiple times which causes currently also **bug** if `headingLabelCallback()` looks like `return 'ONCE ' + text`. The word ONCE will be outputed twice in the toc. My temporary fix is to check for `heading.nodeType`.

Also I am wondering why I have to set `nodeName` and not only `headingLevel` to get levels rendered correctly.

This way I am able to customize label and level.
It would be nice if I could set `obj.attrs = {'data-tooltip': 'usable for styling or for onclick event'}`.

Thank you for your time.

**Comment by k2s** [comment]
Related to #167. If proposed `headingObjectCallback()` will return false or null, this item should be removed from TOC.
