### ISSUE TITLE
module.js:1 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kakaluote444** [tscanlin/tocbot#165]
![image](https://user-images.githubusercontent.com/15668875/69480270-081cf500-0e41-11ea-97d6-af9775e06f0c.png)

**Comment by tscanlin** [comment]
I am not able to reproduce this, could you please provide more info. It looks like its coming polyfill.min.js which this page doesn't include so I'd imagine its coming from an extension perhaps?

**Comment by kakaluote444** [comment]
yes,it comes from my chorme extension plugin,not this plugin problem.it was disappered when i turn off   the my chorme plugin.
