### ISSUE TITLE
Is it possible to add expanding option

### ISSUE THREAD

**Issue by BrambleXu** [tscanlin/tocbot#169]
Right now the heads are collapsed. Only when scrolling to into a specific head, the sub-level of heads will expand. I want an option to set all levels to expand. 

Below is an expanding example.

![image](https://user-images.githubusercontent.com/10768193/69781993-2133f600-11f3-11ea-9d5a-bc3fa7961f2e.png)

Reference: https://github.com/blinkfox/hexo-theme-matery/issues/258

**Comment by tscanlin** [comment]
You can change the collapse depth to 6 and that should handle this. Please comment here if it doesn’t work for you. https://github.com/tscanlin/tocbot/blob/master/src/js/default-options.js#L37
