### ISSUE TITLE
What if the TOC goes off the page?

### ISSUE THREAD

**Issue by supsup** [tscanlin/tocbot#17]
Is there a way to make a scroll bar appear if the TOC is greater than the pages current height?

**Comment by tscanlin** [comment]
yeah, if you use overflow-y: auto it should work:
```
.toc {
    overflow-y: auto;
}
```
Let me know if that works for you. Maybe I should add this as default functionality, what do you think?

**Comment by tscanlin** [comment]
I updated version 2.1.5 to include this by default. Hope that helps! :)

**Comment by supsup** [comment]
That works, but I also had to make sure the container had a min-width of 24%(responsive column width - 1 percent) or the scroll bar would go in and out as you went down the page.

Thanks for the information and the help ;-). Awsome plugin. glad to see your actively working on it.  You can close this bug out.  The rest of this is just my own view/wishful thinking about your plugin.

Wishful thinking #1:
Overall I wish there was a way to just suppress the ugly OS specific scroll bar all together and perhaps to the left have some kind of arrow feature showing up and down arrows centered in the middle of the toc.  (left side so you don't have to worry about width of the column)  The arrow color could be set when the action is not possible --> like a faded out arrow if you cannot go up or down,  and a user set color bordered arrow if you can go down.  Then if you press the arrow, or if you use your scroll wheel inside that column it goes up and down.

Wishful thinking #2 
There should be two way binding between the content and TOC view-port.
Currently I think there is 1.5 way binding:
1) if you scroll down the content the TOC follows.
1.5) if you click a TOC item it jumps the content to the right place.
Full 2 way:
2) if you scroll down the content and the item in the TOC is off the view-port the TOC item is scrolled into view.

I was going to try to do some of this with your code but unfortunately I was on a windows machine and NPM build fails with no error messages.  I was going to try again today on my Linux box.

**Comment by tscanlin** [comment]
Thanks, glad I was able to help you solve your issue. With regard to your points:

#1 I think replacing scroll functionality is outside the scope of this library. But do you know any other libraries or websites that have behavior more similar to what you want?

#2 I think I might know what you're referring to with this. Is this about the funky-ness for items at the bottom of the content? Where the toc can't select them because you can't scroll to them? If so you can add 'margin-bottom: 100vh:' to extend the content so you can scroll to every item. Let me know if this is a different issue.

**Comment by tscanlin** [comment]
I also develop this on Windows so it should work there. But send me any info / logs if it isn't working for you, even just seeing which steps it passes with / without errors would help.

**Comment by supsup** [comment]
When i do npm build it does not do anything.  I have npm 1.4.9 installed perhaps that is the problem?
In your contributing section maybe you can go over the steps to get the code running locally?  I was under the impression I'd just have to type npm build in the cloned source.

#1 I think it is in scope but also kind of extreme. like a theme or something.  Prob not worth looking into right now. 

#2 I can scroll to every item as is, but it's annoying to have to move the scroll bar in the TOC to match where I am in the content (since it does not auto adjust)

**Comment by supsup** [comment]
Sorry I should of opened these as features now that I think about it.

**Comment by tscanlin** [comment]
For #2 I'd generally recommend not having so much content in the toc so that it has to scroll. Maybe split into smaller pages. However, if you made a pull request to add this functionality I'd be happy to help get it merged. Let me know if you're interested (assuming you can get it running locally).

**Comment by supsup** [comment]
The case it happens in mostly is when I don't want the TOC to collapse 'collapseDepth: 3' or higher. It very quickly happens that the TOC will go off the page.

**Comment by tscanlin** [comment]
Yeah, I could imagine that the toc can get long when you dial up the collapseDepth. I don't think I will get around to implementing it in the near term, but I understand your use case and would accept a pull request to add that functionality.

**Comment by supsup** [comment]
OK, still investigating this idea.
