### ISSUE TITLE
Initial display of TOC with n level expanded

### ISSUE THREAD

**Issue by joel-costigliola** [tscanlin/tocbot#172]
Hi,

Thanks for TOCBOT, we are using it for [AssertJ](https://assertj.github.io/doc/), is there an option to display the TOC alread expanded to a certain level (level 1 would work for us)?

I have been playing with `collapseDepth`,setting it to 1 or 2 but that did not achieve what I was looking for.

We using tocbot 3.0.2 (newer versions did not work but as I'm not a frontend expert I haven't figured out why) here: https://github.com/assertj/doc/blob/master/src/docs/asciidoc/user-guide/docinfo-footer.html

Any help appreciated, 
Thanks again for this library

Joel

**Comment by tscanlin** [comment]
Hey Joel, 

That setting should do what you want. Can you share a screenshot and explain how you are expecting this setting to work? I tested on the docs site with `tocbot.refresh({ collapseDepth: 3 })` and it seemed to work.

Sorry for my late response, I just got back from vacation. Let me know if there's any way I can help.

**Comment by joel-costigliola** [comment]
hey @tscanlin, thanks for the reply, hope you had a good break!

Setting collapseDepth: 3 did the trick, now I feel a bit embarrassed :sweat_smile: I thought setting to 2 would unfold the first two levels.

Anyway thanks for the help and for tocbot.

cheers

**Comment by tscanlin** [comment]
Glad to hear that worked!
