### ISSUE TITLE
Active Section Highlighting Section much father down the page

### ISSUE THREAD

**Issue by SaltedyLevity** [tscanlin/tocbot#173]
Hello!
I'm building a site for a hobby (a certain video game) and running into some issues. It's a wordpress-built site as I want to be able to have content contributors of any skill level work on it, and to that point I'm also using Elementor's (pro) page builder.

I _had_ this working properly on the page, until I started to get fancy with it.
https://www.saltedxiv.com/white-mage/whm-guide/

Clicking a link in the ToC jumps to the right spot, but the "you are here" active display is way off/farther down the page and I'm not sure why.

I've tried setting the timeout to 5s just to be extra sure it's not a page loading issue (per suggestion here: #89 (also tried window.onload) and still have that implemented, but it doesn't seem to have corrected the issue. 

Script is referenced and initialized in the footer as the very last thing before he closing </body> tag.

The only clue so far I have is that it seems to get _worse_ the more inner sections I have. Link above has something over 20 I think. This page, an earlier version I copied: https://www.saltedxiv.com/white-mage/white-mage-guide-backup/ has fewer (I think like 6) inner sections and the skew by how far off the active issue is, is less.

Is there just a fundamental conflict with this and Elementor? Or is there anything I can do to improve this? I prefer this ToC implementation over elementor's included one, so I'd really prefer to stick with this if I can get it working - but I have no idea where to look.

I'm a pretty rudimentary novice, and the site is just for fellow gamers, but any help is appreciated!

**Comment by tscanlin** [comment]
I think I found the issue. I added a special option to handle sites that have inner containers. Try: `tocbot.refresh({ ...tocbot.options, hasInnerContainers: true })`

Hope that helps!

**Comment by tscanlin** [comment]
I have a PR open to add a section to the readme for how to solve issues like this:
https://github.com/tscanlin/tocbot/pull/174/files

Let me know if you have any more questions.

**Comment by SaltedyLevity** [comment]
Thank you! I appreciate you both answering my question and updating the troubleshooting section! It's working properly now.

I'll close this issue since i'm set on it! Though I did have another question about styling options (something similar to the optimizely page's setup with parent categories not having the bar before the list item on the higher level headings - but I want to try and learn a bit more before asking the question since as I said, i'm an ultra novice, and don't want to ask a question while just expecting to be spoon fed everything!
