### ISSUE TITLE
Making it work with Ghost

### ISSUE THREAD

**Issue by tahamaddam** [tscanlin/tocbot#175]
The topic is more about asking for help rather than reporting issues

I would like to implement tocbot in my Ghost installation but having hard time to figure out where to put which file. There is *code injection* area in Ghost dashboard and tried to put css and js file there but don't know how to initiate the instance on every page. 

Any help would be great.

Thanks

**Comment by tscanlin** [comment]
Hey, glad to hear you are interested in tocbot. I haven’t used ghost before but will try and help. When you add to the code injection area is tocbot available globally? Also can you link me to an example somewhere?

**Comment by tahamaddam** [comment]
Thanks for offering help. 

Yes, I provided  the **css** and **js** file (those files as mentioned in[ this page](https://tscanlin.github.io/tocbot/) )  globally and then on the instance of the post, initiated the script using this (adding on the footer):
```
<script>
tocbot.init({
tocSelector: '.js-toc',
contentSelector: '.content',
headingSelector: 'h1, h2, h3',
hasInnerContainers: true,
});
<script>
```

But somehow, the posts are not loading. 

My website is under staging but you can see one person implemented the same tocbot in his Ghost post [here](https://vanilla.ghost-o-matic.com/the-editor/) and our discussion on the same matter [here](https://forum.ghost.org/t/scrollable-table-of-content/11474/8)

It seems straightforward for people who know what they are doing but I couldn't yet figure it out. 

Thanks again.

**Comment by tscanlin** [comment]
You might be trying to initiate before the page has loaded. Maybe try wrapping the init
```
document.addEventListener("DOMContentLoaded", function() {
  // code...
}); 
```

**Comment by tahamaddam** [comment]
Thanks. 

I tried to wrap init as you mentioned but still no success

```
<script>
document.addEventListener("DOMContentLoaded", function() {
  tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.js-toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '.content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h2, h3, h4',
  // For headings inside relative or absolute positioned containers within content.
  hasInnerContainers: true,
  });
}); 
</script>
```

Where did I go wrong?

**Comment by tahamaddam** [comment]
Damn, it seems like I didn't mentioned where to add toc under <body>

**Comment by tscanlin** [comment]
Yeah that element must be missing. Do you have an example of this hosted somewhere that you could share a link to?

**Comment by tahamaddam** [comment]
Here is the demo link

https://tahamaddam.com/variables-strings-numbers-and-others/

It seems that I need to make theme level changes? I would like to get the same look and feel as on [tocbot homepage](https://tscanlin.github.io/tocbot/) On the right side along the body and on mobile devices display "menu" button.

**Comment by tscanlin** [comment]
Yeah, you will need to edit the theme to add an element for the toc to render into.

**Comment by tahamaddam** [comment]
I did implement it but there are Css issue regarding the look, feel and functionality. Would you consider helping me out with this as a paid gig? I have very little knowledge of css so don't know where to make changes and how. Thanks.

**Comment by tscanlin** [comment]
I don't have a lot of time to help out on a contract basis but will try and do what I can. I found a couple articles describing adding a sidebar:
https://forum.ghost.org/t/implementing-a-sidebar-to-the-casper-theme/1603
https://github.com/johnpapa/jp-ghost-theme/blob/master/partials/sidebar.hbs

I feel like this CSS is totally something you can learn and it will give you a lot of power for how you present things on the web. You can try playing with the `float` prop to start just in the inspector.

**Comment by tahamaddam** [comment]
Thanks for providing this great open source software but after playing around with Ghost CMS for few days I believe it is not for me. Implementing TOC is just a start, I may end up with more issues later on, as Ghost lacks a lot in plugins and customization is only possible through hard-code rather through GUI (like in Wordpress)

Thanks again.
