### ISSUE TITLE
"Uncaught SyntaxError: Unexpected end of input" when initializing

### ISSUE THREAD

**Issue by jtebert** [tscanlin/tocbot#176]
For simplicity, I'm starting with loading the script from the CDN:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.10.0/tocbot.min.js"></script>

Then initializing it [as shown in the demo page](https://tscanlin.github.io/tocbot/#usage):

```js
<script>
      tocbot.init({
        // Where to render the table of contents.
        tocSelector: '.js-toc',
        // Where to grab the headings to build the table of contents.
        contentSelector: '.js-toc-content',
        // Which headings to grab inside of the contentSelector element.
        headingSelector: 'h1, h2, h3',
        // For headings inside relative or absolute positioned containers within content.
        hasInnerContainers: true,
      });
    </script>
```

I also created dummy HTML elements to work with this:
```html
<div class="js-toc"></div>
<div class="js-toc-content">
    <h2>test 1</h2>
    <h2>test 2</h2>
</div>
```

But I'm getting the console error when I load the page: `Uncaught SyntaxError: Unexpected end of input` (and it fails to initialize/work at all.) I also got this when trying to use the "real" content of my page.

My guess is that it's somehow mis-parsing the contents of the headers? The error isn't very informative, which makes it hard to debug. Any ideas why this might be happening?

For further context, it's a Jekyll website built with [Just the Docs](https://pmarsceill.github.io/just-the-docs/)

**Comment by tscanlin** [comment]
That means you have a syntax error in your JS code most likely. Can you link me to a live example of this? Without it I won't be of much help.

**Comment by jtebert** [comment]
It's on [this github branch](https://github.com/jtebert/document-everything/tree/scroll-toc). In particular, the JS is at the [end of this file](https://github.com/jtebert/document-everything/blob/scroll-toc/_layouts/default.html).

It's definitely coming from the `init` call (no errors if I comment that out), but the syntax for that is so straightforward that it seems odd to fail there.

**Comment by tscanlin** [comment]
Have you tried commenting out everything except tocbot? The init call works fine in the tocbot docs so I’d expect it’s something else. A live example would be helpful.
