### ISSUE TITLE
Some head2\3 now show in the toc? Need help

### ISSUE THREAD

**Issue by inevity** [tscanlin/tocbot#177]
Look at https://blog.approachai.com/2019nian-hei-wu-hai-tao-ji/   
inspect the` <h1 id="toc-title-5" tabindex="-1">二、海淘记</h1>,` then the h2/h3 head did not show in the toc.
Note: Have set hasInnnerContainers as true,headingSeletor as h1,h2,h3.

**Comment by tscanlin** [comment]
I think they are there but just hidden, try setting `tocbot.refresh({ ...tocbot.options, collapseDepth: 6 })`

`collapseDepth: 6` should expand everything not just the current section.

**Comment by inevity** [comment]
Thank your help.
