### ISSUE TITLE
How to make it work with Wordpress?

### ISSUE THREAD

**Issue by tahamaddam** [tscanlin/tocbot#178]
I would love to implement this on my Wordpress based website but need guidance on how to implement this? Does this have any official Wordpress plugin?

**Comment by tscanlin** [comment]
There is no official wordpress plugin unfortunately, to implement this you would need to be comfortable editing templates and adding css to style it. This is an interesting feature request though, thanks for suggesting it. I can try to help if you link me to a working example of your site.

**Comment by tahamaddam** [comment]
Thanks for the reply and willing to take interest in the implementation. 

As far as my CSS skills are concerned, consider it at level-0. I know how to add the .js and .css file into header/footer area, but to initialize it and style it, I have no clue. 

If you are willing to help, I can give you username/password for the demo Wordpress website? are you interested? Thanks a lot.

**Comment by tscanlin** [comment]
Sure. I'll check it out.

**Comment by tahamaddam** [comment]
Thanks a lot. Just sent you an email(at address available at your website) with the details.
