### ISSUE TITLE
Child combinator selectors allowed?

### ISSUE THREAD

**Issue by bradryanbice** [tscanlin/tocbot#182]
Is it possible, or can it be built in, to allow for child combinator selectors when choosing `headingSelector`? I have embedded content that I _don't_ want to be captured, and it is being picked up currently.

For example:
```
headingSelector: '> h2',
```
The above would select only `h2` elements that are direct children of `tocSelector`.

Another solution could be to set the number of levels down the document the script searches, through the DOM tree.

**Comment by tscanlin** [comment]
Yeah, this option could certainly be added. Currently it selects headings from the `tocSelector`. Would you be interested in adding an option to select from the document instead to solve your use case?

Then you could do `headingSelector: '.js-toc-content > h2',` The PR would be relatively straight forward. 

The relevant line is here: https://github.com/tscanlin/tocbot/blob/master/src/js/parse-content.js#L110

**Comment by bradryanbice** [comment]
So that would combine `contentSelector` and `headingSelector`, correct? It might make sense to do that? 

It doesn't particularly help my (admittedly unique) use case, where I'm embedding markup examples in my content area. So I'd still target the same content area on the page, but I'd just want to limit how far deep into the DOM I'd want the script to look.

**Comment by tscanlin** [comment]
I don't think I understand the use case here very well. I'm going to close this for now but I'm open to revisiting it later if more people comment that they want this.
