### ISSUE TITLE
CSS Grid and tocbot

### ISSUE THREAD

**Issue by kapooramit** [tscanlin/tocbot#184]
Hi,

I am using CSS grid for my page layout. The TOC created using tocify is a grid-item. The content is also a grid-item. I need TOC , Sidebar, Headers, And TOCIFY to be sticky. So adding max-height and overflow-y:scroll to the grid-items solved the issue. But now, tocify doesn't expand when I scroll down. What is shown in the tocify above the first fold is all I see and it doesn't work like it should. Without the max-height and overflow, it works fine. 

Not the full HTML and CSS, but simple design layout of my code is here: https://codepen.io/amitkapoor/pen/GRpMVwv.

Can you tell me how can I achieve what I need?

**Comment by tscanlin** [comment]
Sorry but I can't really understand what layout you are trying to achieve without a full example. Can you post that and I can see what I can do to help?

**Comment by kapooramit** [comment]
Thanks. I just updated example pen. Kindly look at it. With max-height and overflow-y, I have made the content pane scrollable and rest all are just kind of fixed/sticky. 

The goal is to use CSS grid and have everything at fixed place with content pane scrolling. Footer would show up when I reach the end of  content. 
https://codepen.io/amitkapoor/pen/GRpMVwv.

**Comment by tscanlin** [comment]
To achieve this, wouldn't you just need to add the footer to the bottom of `.ht-content` or optionally another wrapper to wrap the content and the footer (as siblings) in a `overflow-y: scroll` so that the footer only shows after all content has scrolled. Does that make sense and help achieve what you want?

**Comment by kapooramit** [comment]
I have removed the footer altogether because I can add it at the end of content later like you suggested. Still no go. Please see: https://codepen.io/amitkapoor/pen/YzyEpQE. I have spent two days to try different ways to achieve any setup that makes tocify work as it does otherwise but no go :-) . 

Thanks.

**Comment by tscanlin** [comment]
If I take off the `max-height:90vh;` it seems to be working right. Is that still not what you expect?

**Comment by kapooramit** [comment]
I expect it to work with header and sidebar and tocify output itself fixed. Only the content should scroll.

**Comment by tscanlin** [comment]
Then those items need to have position fixed on them so that they don't scroll.

**Comment by kapooramit** [comment]
Yes but then, the grid-item behavior is disabled. CSS grid items won't behave like themself if they use position property.  I might have to end up not using CSS grid and use position element for the complete layout to get tocify work if there is no solution to my issue here.

**Comment by tscanlin** [comment]
Yeah, you will need to rethink your layout and use position fixed for this. Anchor links on the page won't work right if you have containers with `overflow-y: auto` etc.

**Comment by kapooramit** [comment]
So, I got it working by letting go CSS grid and using Flexbox instead. It was not convenient but works. Thanks.
