### ISSUE TITLE
Are multiple tocbot instances (for tabs scenario) possible?

### ISSUE THREAD

**Issue by winstonsmith1789** [tscanlin/tocbot#186]
Hi,

Thanks for this great package.

I managed to add two instances that initiate correctly and without any console warnings or errors, using `each()`:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/47567591/81830609-48b11d80-950a-11ea-8cd7-09e56b4b109f.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/47567591/81830637-52d31c00-950a-11ea-9978-523d42b3edb9.png">

The code I used:

```javascript
let tocSelector, contentSelector = '';
$('.toc-source').each(function (i) {
	i++;
	tocSelector = '#toc' + i;
	contentSelector = '#' + $(this).attr('id');
	console.log(i);
	console.log(contentSelector);
	console.log(tocSelector);
	tocbot.init({
		tocSelector: tocSelector,
		contentSelector: contentSelector,
		headingSelector: 'h1, h2, h3, h4',
		headingsOffset: 180,
		orderedList: false,
		hasInnerContainers: true,
	});
});
```

However, the active classes are not applied to the TOC lists on scroll. As you can see, the initial active li remains active. I looked through the options, but couldn't find anything.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/47567591/81829954-79dd1e00-9509-11ea-9d5d-93178c2be2cc.png">

Is there any way to iterate through multiple instances?

Console log looks right as well. My elements are being targeted correctly: 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/47567591/81829342-cc6a0a80-9508-11ea-8c79-70a3cf49c844.png">

Thank you.

**Comment by tscanlin** [comment]
Why not just re-initialize with the new content on tab change?

**Comment by winstonsmith1789** [comment]
Well, there's a very simple reason that made that technically unfeasable: I don't know Javascript. So it never occurred to me to attempt to combine the tabs code with tocbot. Thank you for the suggestion, I will get to it and report back if I have any progress. 

Thanks again for this great component.
