### ISSUE TITLE
Update "Include CSS" documentation

### ISSUE THREAD

**Issue by Brian-Pho** [tscanlin/tocbot#187]
I tried importing the styles using
```
@import 'tocbot/src/scss/tocbot-core';
@import 'tocbot/src/scss/tocbot-default-theme';
```
as stated in the [documentation](https://tscanlin.github.io/tocbot/#include-css) but this is outdated and doesn't work. The filenames have changed and the updated documentation should be
```
@import 'tocbot/src/scss/tocbot';
```
I've tested the updated import and it works.

**Comment by tscanlin** [comment]
Awesome, thanks for the PR! :)
