### ISSUE TITLE
Feature: How to deal with huge footers?

### ISSUE THREAD

**Issue by supsup** [tscanlin/tocbot#19]
When a site has a huge footer since the left side is fixed it will go over the footer.

I was thinking maybe making a new class called:  toc-footer-stopper
When the footer id is close to the view-port remove the fixed class from the fixed class target and add the footer-stopper class which makes the toc absolute to the bottom of it's container, and when the footer is scrolled back out of the view-port remove it and add back the fixed class?

Is this a good approach or is there a better way?

**Comment by tscanlin** [comment]
Couldn't you just do `.toc { max-height: calc(100% - <footer-height>px); }`?

**Comment by supsup** [comment]
I don't think so since the toc is fixed?

**Comment by supsup** [comment]
I reviewed 
https://developer.mozilla.org/en-US/docs/Web/CSS/calc
and see how i was misusing this.  

The problem then would be on long docs the toc would be cut short for most of the page just to handle the footer at the end?...some footers are massive!

**Comment by tscanlin** [comment]
Yeah, I think I see what you're saying now. Why not just change the z-index of the footer to be above the toc so the toc just disappears behind it when you scroll down so far?

**Comment by supsup** [comment]
I will try that.

**Comment by tscanlin** [comment]
Did this work for you?

**Comment by supsup** [comment]
Sorry I thought I responded to this the other day but I guess I forgot to hit submit:

Yes it works, but you have to also make sure your footer has a position set--at least if your using bootstrap.
