### ISSUE TITLE
Tocbot is useless with narrow windows

### ISSUE THREAD

**Issue by 71GA** [tscanlin/tocbot#191]
I found out that tocbot is only active if the window is wide enough e.g.:
![Screenshot_2020-06-10_09-43-51](https://user-images.githubusercontent.com/8915807/84241120-53f26b80-aaff-11ea-95af-2cf79eec15b9.png)
When I narrow the window a bit, tocbot is moved to the top but is still active _(it should be expanded at this point **(!)** otherwise it is totaly useless, because when we click any header inside tocbot, view immediately shifts to that header, we can't see tocbot any more and are unable to e.g. click any kind of subsection in tocbot)_:
![Screenshot_2020-06-10_09-44-09](https://user-images.githubusercontent.com/8915807/84241262-8c924500-aaff-11ea-8aaa-a4c5dca74cee.png)
When I decrease window width further, tocbot is turned off **(!)** and at this point table of contents is usefull, but it is ugly because style is different now:
![Screenshot_2020-06-10_09-44-30](https://user-images.githubusercontent.com/8915807/84241788-425d9380-ab00-11ea-8077-008711326133.png)
**Conclusion:** Tocbot should always be active, but should expand **(!)** at the same time table of contents is moved at the top of the page. Otherwise it is useless in a transitional period.

**Comment by tscanlin** [comment]
You need to add css to handle narrow widths. See the documentation site, it works fine on mobile.
