### ISSUE TITLE
Missing a stripped-down simple working example

### ISSUE THREAD

**Issue by carbontracking** [tscanlin/tocbot#193]
Hello,

I've been trying to get a demo of this working for the last couple of hours without any joy.

Would it be possible to ask for a simple, simple, simple working example with absolutely minimal html that shows the operation of this as it works on https://tscanlin.github.io/tocbot/

I would so appreciate it.

Best regards / Colm

**Comment by tscanlin** [comment]
I think the documentation site is already pretty simple, not sure how I'd make it more simple and stripped down than that..
