### ISSUE TITLE
Render to multiple selectors/elements?

### ISSUE THREAD

**Issue by dubfonik** [tscanlin/tocbot#195]
I'm trying to get tocbot to work on both desktop and on mobile (via off-canvas menu). It appears that it will only render to one element - I'm assuming the first detected.

Is it possible that tocbot either:

1. Outputs to all elements with the defined selector.
eg. tocSelector: '.js-toc' //renders to all elements with .js-toc selector
2. Allows for an array in the options
eg. tocSelector: ['.js-toc','.js-toc-mobile', '#another-toc-element] //renders to the first detected element of each selector/ID

If there's an existing workaround, I'd love to know :). Great work by the way!

**Comment by tscanlin** [comment]
This isn't currently possible. You can have the off canvas men use the same element and just toggle the styling via CSS, or you could look at the screen width on page load and target a different element for desktop/mobile.

**Comment by dubfonik** [comment]
Ok, thanks for replying. I decided to go with a JS method. I'm not very good at JS, but I wrote this script to achieve what I needed. I'll leave it here for anybody else needing to accomplish the same. Just change the "1200" for window width that suits your need.

```
// RUN TOCBOT - SET SELECTOR & HEADING HEIGHT
function runTocbot(selector) {
  tocbot.init({
  // Where to render the table of contents.
  tocSelector: selector,
  // Where to grab the headings to build the table of contents.
  contentSelector: '.content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h1, h2, h3',
  // For headings inside relative or absolute positioned containers within content.
  hasInnerContainers: true,
  scrollSmooth: false,
  headingsOffset: 80
  });
}


// DETECT WINDOW WIDTH
function detectWindowWidth() {
  // Get the width of the viewport
  let windowWidth = window.innerWidth;
  
  // If viewport width is less than 1200...
  if (windowWidth <= 1200) {
    
    // and scope isn't mobile...
    if (tocbotScope != "mobile") {
      
      // set scope to mobile
      tocbotScope = "mobile";
      
      // destroy existing tocbot instance
      if (tocbotScope == 'undefined') {
      tocbot.destroy();
      }
      
      //run tocbot
      runTocbot('#tocbot-mobile')
    }
  }
  
  // Otherwise...
  else {
    // if scope isn't desktop...
    if (tocbotScope != "desktop") {
      
      // set scope to desktop
      tocbotScope = "desktop";
      
      // destroy existing tocbot instance
       if (tocbotScope == 'undefined') {
      tocbot.destroy();
      }
      
      // run tocbot
      runTocbot('#tocbot-desktop');
    }
  }  
}

// Declare tocbot selector as undefined
let tocbotScope;

// Wait for window to load
window.addEventListener("load", (event) => {
  detectWindowWidth();  
});

window.onresize = detectWindowWidth;
```
