### ISSUE TITLE
Neither Jumping to correct sectiona nor highlighting the tocbot entry

### ISSUE THREAD

**Issue by kapooramit** [tscanlin/tocbot#198]
I am using tocbot and it was working great if I recall correctly. But suddenly - I don't know why it doesn't jump to the right heading on clicking until after I have clicked a heading in rendered toc a couple of times and then the heading (in rendered toc) doesn't get highlighted too until page slowly reaches to the right heading. However, if I scroll down a long page, all entries in the rendered toc get highlighted correctly and at the right time. 

What could have caused this? This is a protected website and if you think you need to look at the issue, kindly let me know and I will open it for you. Please help. 

Thank you.

**Comment by tscanlin** [comment]
I imagine it could be some scroll listener or something, difficult to tell without seeing the issue though.

**Comment by kapooramit** [comment]
Hi Tim,

Because this is protected content, I could not share the URL here and thus sent to your email. 

Clicking the tocbot toc works initially and then stops behaving weirdly. I am kind of sure that something in my code is doing this but don’t know what and why. I do have custom scroll listener function added to help me calculate sidebar height when header moves up and fixed part of header gets sticky.

-Amit

**Comment by kapooramit** [comment]
One thing I forgot to add - I did try disabling my custom scroll functions - but it didn't make a difference in the issue.

**Comment by kapooramit** [comment]
Ah! This is weird. It was CSS declaration for making enabling smooth scrolling in Firefox that caused this. Once I deleted it, no weird jumping/clicking. I wonder why that is the case. Maybe when you look at the my site, you can tell me about that. 

Also, how do I enable smooth scroll when using tocbot for tocbot links? This is my initialization code but smooth scroll doesnt make a difference:

```
  tocbot.init({
      tocSelector: '.js-toc',
      contentSelector: '.js-toc-content',
      headingSelector: 'h2, h3',
      hasInnerContainers: false,
      collapseDepth: 3,
      scrollSmooth: true ,
      scrollSmoothDuration: 5000,
      scrollEndCallback: function (e) { },
  });

```

**Comment by tscanlin** [comment]
It should do smooth scrolling by default without needing any extra config.

**Comment by kapooramit** [comment]
Thanks Tim. I have reset the permissions on the link I shared assming you don't plan to look at it anymore.
