### ISSUE TITLE
activeLinkClass not working when linkClass used

### ISSUE THREAD

**Issue by akshuvo** [tscanlin/tocbot#199]
I am using this code:

tocbot.init({
    tocSelector: '.js-toc',
    contentSelector: '.js-toc-content',
    headingSelector: 'h2,h3',
    hasInnerContainers: false,
    linkClass: 'px-0 py-1 nav-link text-small t',
    listClass: 'nav flex-column',
    listItemClass: 'nav-item',
    activeLinkClass: 'active',
    orderedList: false,
});

**Comment by tscanlin** [comment]
Can you try just using `nav-link` for `linkClass` and add the others in `extraLinkClasses`, that may fix it.
