### ISSUE TITLE
Right aligning colored border and proper scroll behavior

### ISSUE THREAD

**Issue by busywhistling** [tscanlin/tocbot#200]
Hi,
I'm trying to use tocbot on my website. I'd like to keep the table of contents in a fixed sidebar on the left, with the TOC right aligned and the colored (green) border to the right of it. I also failed to get proper scrolling (& collapsing of subheadings) behavior on my website (the last entry seems to be always highlighted). [Here](https://busywhistling.github.io/sample.html) is a sample page. I'm not very familiar with css and even more so with js. Could you let me know how I can go about getting the desired behavior?

My configuration `/static/tocbot/custom.js` is the following.
```
tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '#content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h2, h3',
  // For headings inside relative or absolute positioned containers within content.
  hasInnerContainers: true,
  // How many heading levels should not be collapsed.
  // For example, number 6 will show everything since
  // there are only 6 heading levels and number 0 will collapse them all.
  // The sections that are hidden will open
  // and close as you scroll to headings within them.
  collapseDepth: 0,
  // Smooth scrolling enabled.
  scrollSmooth: true,
  // Smooth scroll duration.
  scrollSmoothDuration: 420,
  // fixedSidebarOffset can be any number but by default is set
  // to auto which sets the fixedSidebarOffset to the sidebar
  // element's offsetTop from the top of the document on init.
  fixedSidebarOffset: 'auto',
  // orderedList can be set to false to generate unordered lists (ul)
  // instead of ordered lists (ol)
  orderedList: false,
  // If there is a fixed article scroll container, set to calculate titles' offset
  scrollContainer: null,
});
```

**Comment by tscanlin** [comment]
I think you just need the `hasInnerContainers` as true. Try this in the console on that page:
```
tocbot.refresh({ ...tocbot.options, hasInnerContainers: true })
```

**Comment by tscanlin** [comment]
or maybe you need to defer the loading of tocbot until later on the page. You already had that option but a `tocbot.refresh()` in the console seems to fix it.

**Comment by tscanlin** [comment]
Can you try moving tocbot.init after the katex stuff?

**Comment by busywhistling** [comment]
Interesting, moving `tocbot.init(...);` after the katex stuff doesn't work at all (somehow tocbot is not loaded). And keeping the earlier scripts with a `tocbot.refresh();` at the end also doesn't help. In the current [version](https://busywhistling.github.io/sample.html), I have the following scripts at the end:
```
<script src='/static/katex/katex.min.js'></script>
<script src='/static/katex/custom.js'></script>
<script src='/static/tocbot/tocbot-4.11.1.min.js'></script>
<script src='/static/tocbot/custom.js'></script>
<script defer>tocbot.refresh();</script>
```
However, as you can see, it doesn't work. Calling `tocbot.refresh();` in the console solves the problem, though.

**Comment by tscanlin** [comment]
Could you try wrapping in:
```
window.addEventListener('DOMContentLoaded', (event) => {
    console.log('DOM fully loaded and parsed');
    tocbot.init(...)
});
```
Or if that doesn't work maybe a setTimeout is required to delay it. That's not ideal, but everything seems to work fine without the `katex/custom.js` stuff.

**Comment by busywhistling** [comment]
Yes, wrapping that code indeed helps, thanks! Interesting, `katex/custom.js` makes a number of substitutions for some custom latex macros. Didn't think that would interfere with the toc, but there indeed seems to be some interaction... Any reason you mention this solution is not ideal?

**Comment by tscanlin** [comment]
Glad to hear that worked! Listening for `DOMContentLoaded` is fine to use and sometimes necessary. I was saying setTimeout isn't usually ideal to use since its not as predictable.

**Comment by busywhistling** [comment]
That works great! Thanks a lot!
