### ISSUE TITLE
How are we supposed to run tocbot in nextjs

### ISSUE THREAD

**Issue by rodbs** [tscanlin/tocbot#202]
I'm trying to run it within the head section and also as an independent script, but I always get 
`TypeError: Cannot read property 'init' of undefined`

```
import * as tocbot from 'tocbot';

if (!tocbot) {
  tocbot.init({
    // Where to render the table of contents.
    tocSelector: '.js-toc',
    // Where to grab the headings to build the table of contents.
    contentSelector: '.js-toc-content',
    // Which headings to grab inside of the contentSelector element.
    headingSelector: 'h1, h2, h3',
    // For headings inside relative or absolute positioned containers within content.
    hasInnerContainers: true
  });
}

export default tocbot; 
```
 
thx

**Comment by tscanlin** [comment]
If you are using with react / next.js you can see how I use Tocbot for its own documentation here: https://github.com/tscanlin/tocbot/blob/master/src/components/Template/Tocbot/index.js

Hope that helps!

**Comment by rodbs** [comment]
Thanks. I'm still fighting a bit with the styling and positioning but I think I've finally made it work!!
