### ISSUE TITLE
Cannot read property 'className' of null

### ISSUE THREAD

**Issue by rodbs** [tscanlin/tocbot#204]
I've observed that when I use lists (ul, ol) in the html, I'm getting this error:

``` 
 Uncaught TypeError: Cannot read property 'className' of null
    at Object.updateToc (build-html.js:210)
    at HTMLDocument.<anonymous> (index.js:164)
    at index.js:74
```
 And the error in the build-html.js is in:
```
if (activeTocLink.className.indexOf(options.activeLinkClass) === -1) {
        activeTocLink.className += SPACE_CHAR + options.activeLinkClass
      }
```
I'm not sure if I'm doing something wrong or it's related to the css framewrok I'm using (chakra-ui) (but I've tried out standard html I'm also getting these errors)

**Comment by tscanlin** [comment]
Hmm, that is strange.. Can you link me to a reproduction of this issue? Also, what are the options you are using?

**Comment by rodbs** [comment]
I'll try to create a reproduction of the component

In the meantime the options I'm using are these:
```
const TOCBOT_HINTS = {
  tocSelector: '.js-toc-hints',
  contentSelector: '.js-toc-content',
  headingSelector: 'h4',
  positionFixedSelector: '.js-toc-hints',
  includeHtml: true,
  hasInnerContainers: true,
  isCollapsedClass: null
 };
```
Basically I use tocobt to get the title of the components rendered. Each component has buttons, and when I render them it's ok, but when I start playing with the buttons inside each component is when I get the error. It's like changing states in the components trigger the error

**Comment by rodbs** [comment]
I've uploaded a demo here:
https://github.com/rodbs/nextjs-mdx-remote

If  you go to localhost:3000/toc and click on 'next' button you'll reproduce the error
I think this error started to happen when I upgraded chakra-ui from rc5 to rc7 a few days ago

Anyway, I'm getting another error in this demo I'm not getting in my production project:
```
Warning: Prop `id` did not match. Server: "9gz3NtVyr" Client: "m6kfwuSgp"
```

Thx

**Comment by tscanlin** [comment]
Ok, didn't realize you were using nextjs, the docs site for this project also uses next.js, so you can try to borrow this code and use it: https://github.com/tscanlin/tocbot/blob/master/src/components/Template/Tocbot/index.js.

Also if it still has issues the state changes may be causing re-rendering which messes up event listeners. Using `shouldComponentUpdate` or a `PureComponent` may help to fix this issue. Let me know how it goes or if you still have issues. https://reactjs.org/docs/react-component.html#shouldcomponentupdate

Good luck!

**Comment by rodbs** [comment]
I guess it's what you say with event listeners.
I've implemented this using useCallback. Now I'm not getting the error but the scrolling in tocbot doesn't work. 
What can I do? thx

```
  const toc = useCallback(() => {
    if (tocbot && typeof window !== 'undefined') {
      tocbot.init(Object.assign({}, TOCBOT_HINTS));
    }
  }, []);
  
  useEffect(() => toc(), []);
```

**Comment by tscanlin** [comment]
Have you tried with just `useEffect` and without using `useCallback`?

**Comment by rodbs** [comment]
Yes, useEffect is was I using initially when I started this issue.

I think the issue is related with the event listeners you mentioned at the beginning. I think useCallback is a way to use PureComponents  in functional components using hooks. I need to dig into it a bit more but I just wondering if you have an approach to "encapsulate" these event listeners tocbot uses.

**Comment by tscanlin** [comment]
Yeah. what do you mean by "encapsulate"?

**Comment by rodbs** [comment]
I meant using useCallback or a PureComponent. I need to dig into it but I just wondering if you have any examples using this approach.

**Comment by tkrotoff** [comment]
I have the same issue when using codesandbox.io: https://codesandbox.io/s/github/tkrotoff/bootstrap-input-spinner/tree/codesandbox.io

I cannot reproduce this when not using codesandbox.io: https://github.com/tkrotoff/bootstrap-input-spinner

**Comment by tscanlin** [comment]
Hmm, I checked out that link and wasn't able to reproduce the issue. What browser are you using? Do I need to trigger it somehow?

**Comment by tkrotoff** [comment]
@tscanlin just found out that this happens only when you are logged into your codesandbox.io account! (macOS with Chrome 88 and Firefox 85) when you simply scroll.

I couldn't reproduce this when not logged to my codesandbox.io account (with Chrome 88, Firefox 85 and Safari 13.1.2).

![Screen Shot 2021-02-19 at 10 01 53](https://user-images.githubusercontent.com/643434/108483002-7d70b300-729a-11eb-9e99-d2fe341fe858.png)

Definitely something codesandbox.io is doing under the hood.

**Comment by tscanlin** [comment]
Thanks for investigating. I’m going to leave this issue open until we have a better idea of all the cases that may cause this issue.

**Comment by tscanlin** [comment]
I'm going to close since it's been over 6 months but we can reopen if this starts to be a bigger issue.

**Comment by monkey-papa** [comment]
Brother, I have also encountered the same problem now. When I open a page, it works normally, but when I return to the home page and open the same page and start scrolling, it starts to report errors

**Comment by monkey-papa** [comment]
Already fixed, I realized it was my problem and didn't notice that the blogger had updated to version 18 and I was still using the old one
