### ISSUE TITLE
Scrolling monitoring

### ISSUE THREAD

**Issue by liwuming** [tscanlin/tocbot#209]
Hello, when I set iscollapsedclass: 'collapsed' and collapsibleclass: 'collapsed', to display all the titles, if there are more than one title, a scroll bar will appear. You can monitor the scroll bar. Which area the scroll bar displays will display the corresponding title of the area?

**Comment by tscanlin** [comment]
I'm not sure I know what you mean. Can you share a link to an example or a pic that highlights what you are describing?

**Comment by liwuming** [comment]
I'm sorry, I'm from China, my English level is very poor, I like this plug-in very much, but I found a deficiency, in displaying all the titles, and when a lot of titles appear scrollbars, they won't scroll with the scrollbars, I don't know if you can understand what I mean
[example ](https://juejin.cn/post/6844904080809164813)
![这里是图片描述](https://cdn.ibiancheng.net/images/common/juejin.png)
![这里是图片描述](https://cdn.ibiancheng.net/images/common/demo.png)

**Comment by tscanlin** [comment]
Hi, thanks for explaining the issue. I think I understand what you are looking for and it may have already been solved in this PR when someone else had a similar issue as you: https://github.com/tscanlin/tocbot/pull/197

It should keep the toc scroll in sync automatically by default:
https://github.com/tscanlin/tocbot/pull/197/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R216

Maybe that along with the discussion in this issue will be helpful: https://github.com/tscanlin/tocbot/issues/114#issuecomment-651306940

But the way you implemented seems to work well too. Let me know if you are still having trouble with this.

**Comment by liwuming** [comment]
Thank you very much for taking time out of your busy schedule to reply and give me directions。
