### ISSUE TITLE
Initialize tocbot twice on a page

### ISSUE THREAD

**Issue by dmitry1704** [tscanlin/tocbot#210]
Hi,

Thanks for this great plugin.

Is it possible to initialize Tocbot twice on a page without them conflicting? I'm thinking about having two separate instances, one for mobile devices that will display as navbar and one for desktops that will display on the side.

Thank you for your advice,
Dmitry

**Comment by tscanlin** [comment]
Hey, thanks for the question. Currently this is not possible, only one instance is allowed.

Couldn't you just look at the viewport size and only initialize the one that is needed based on that?
