### ISSUE TITLE
Scrolling to a section by clicking the link in ToC doesn't consistently update the active link until the user manually scrolls

### ISSUE THREAD

**Issue by Slapbox** [tscanlin/tocbot#211]
It works fine on the demo/docs site (https://tscanlin.github.io/tocbot/) but in our use case I'm seeing the active styles not being applied unless the user manually scrolls at least 1px up or down after clicking the ToC link.

Any ideas?

Thanks for sharing this really neat library!

**Comment by tscanlin** [comment]
Hmm, this is a peculiar issue.. Do you have a link somewhere that reproduces this?
You could try passing in / adjusting this option to see if it helps:
https://github.com/tscanlin/tocbot/blob/master/src/js/default-options.js#L47

Glad you like tocbot and hope that helps!

**Comment by Slapbox** [comment]
Whoops, I thought I replied to this! Unfortunately I don't have a link I can share right now, but I did get it working.


Bumping that value even up to just `2` fixed the issue, but I ended up removing that option because I managed to get it working without including it.

I'm not entirely certain what fixed it, but I believe increasing the `scrollSmoothDuration` to `2000` may have been the trick - it's a pretty long page.

Thanks so much for sharing tocbot!

**Comment by tscanlin** [comment]
One thing that may cause this is changing the zoom level. You could try that to see if it reproduces the issue. Not really sure how to address that one but hopefully it's an edge case if that is even the issue. Anyway, glad you figured it out!

**Comment by Slapbox** [comment]
I don't think it was a zoom thing, definitely seems like just an edge case! Great library, thanks again!
