### ISSUE TITLE
Parent Class / Has Sub-Menu

### ISSUE THREAD

**Issue by ezadoo** [tscanlin/tocbot#212]
I‘ve been working on the integration of tocbot into an sidebar-menu, but I ran in an problem when I want to use the usual way for indicating sub menus (nested menus) by adding an class to the parent element (like „has-submenu“).

I think, as it is fairly common scenario that the depth of the menus is varying, it would be really useful if an class would be added to the parent directly by tocbot so this element could be styled differently.

As another improvement an additional isCollapsed-Class could be applied to the parent (or instead of the sub-menu element itself), so the indicator can be styled differently when not collapsed.

Currently I’m adding a class to each parent element with an separate function, and I need to implement an mutationObserver for the collapsed-class too. But this isn’t an good solution as I need to reinit tocbot for different screen sizes.

**Comment by tscanlin** [comment]
Hello, thanks for your interest in this project. It is a little difficult to understand what you mean without seeing an example. Do you have one that you could link to? Or could you post a screenshot to show the effect you are looking for?

**Comment by ezadoo** [comment]
Thanks for this quick response. The indicator is could be something like an arrow, that is shown only when there are sub-menus.

Link to codepen demo: https://codepen.io/ezadoo/pen/jOMZgjj

On the static part underneath the toc the open-class on the parent rotates the arrow (Category 5), like I mean it would be useful

**Comment by tscanlin** [comment]
Couldn't you just use the css `:not` selector, like `:not(.is-collapsed)` to select the containers that are open?

**Comment by ezadoo** [comment]
Sorry, maybe I haven’t explained exactly what I meant. Addressing the sub-menu itself, if it’s collapsed or not, isn‘t my problem, that’s working as intended. But as I want to indicate that a list-item has children or not (has sub-menu) I need to address the parent, which can’t be done with css (at least at the moment, as the :has()-selector isn’t implemented in any browser).
So the same applies to the isCollapsed-class on the sub-menu so the indicator on the parent can’t be altered in the not-collapsed state with css only.

I haven’t looked into the code of tocbot very deeply yet, but I think it wouldn’t be too much work to add an additional class to the parent list-item if an sub-menu is added or the collapsed-class is added.

I thought this is the usual way for menu structures, as nearly every CMS or menu-framework is creating a structure this way so it would be a great improvement if tocbot handles it the same way.

**Comment by tscanlin** [comment]
Instead of having the pseudo elements on the list item, is there any reason that the pseudo elements to create the arrow can't be used in the link (`a`)? Then it should be possible to use the classes that are already present without having to use `has:()`.

**Comment by ezadoo** [comment]
As I said, I haven’t looked in to the code of tocbot very deeply, but I think it could be done when an different class is applied to the `a`, if there is an sub-element. But without a different class on a previous element, if it’s the parent `li` or an `a`, I think it’s impossible as CSS doesn’t have ascending selectors, which would be necessary.

Maybe I’ll find some time to create a pr for addressing this feature, but for the moment I’m solving the problem with some extra js and mutationObserver for the collapsing.

Below I’ve added my code below, but no no classes exist for the parent element and the collapsed state on the parent I’ve set them to `toc-sub` for the parent class and `par-not-open` for the collapsed class on the parent. I hope I’ve changed all classes to the standard-value.
So simply `tocbotParent();` needs to be called whenever tocbot is initialized or refreshed.

`function tocbotParent () {

var tocbotParEl = document.querySelectorAll(".toc-list > .toc-list-item > ol, .toc-list > .indexnav-item > ul");
var tocbotParState = document.querySelectorAll(".toc-list > .toc-list-item > .is-collapsed");

for (var i = 0, len = tocbotParEl.length; i < len; i++) {
  tocbotParEl[i].parentNode.classList.add("toc-sub");
}
for (var i = 0, len = tocbotParState.length; i < len; i++) {
  tocbotParState[i].parentNode.classList.add("par-not-open");
}
for (var i = 0; i < tocbotParEl.length; i++) {
  tocbotObserve(tocbotParEl[i]);
}

function tocbotObserve(t) {
  let prevState = t.classList.contains('not-open');
  var observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
               if (mutation.attributeName === "class") {
                 const currentState = mutation.target.classList.contains('not-open');
            if (prevState !== currentState) {
                prevState = currentState;
              if (currentState) {
                mutation.target.parentNode.classList.add("par-not-open");
              } else if (!currentState) {
                mutation.target.parentNode.classList.remove("par-not-open");
              }
           }
        }
    });
  });
  var config = {
    attributes: true
  };
  observer.observe(t, config);
}
}

tocbotParent();`

Link to working codepen (the options are different to match my css): [Codepen](https://codepen.io/ezadoo/pen/jOMZgjj)

**Comment by tscanlin** [comment]
Thanks for sharing your code example. If you could work on a PR to implement the desired behavior that would be great.

**Comment by rmit-hwilcox** [comment]
I would also very much like to  know how to do this... Is it possible somehow??? I basically want the top level header to stay highlighted while the sub menu items get scrolled through... with the below code... I would want 'Top Link1' to keep its 'is-active-link' class until 'Sub Link 3' has scrolled off the windows / 'Top Link2' has started.... I hope that makes sense

**<h2>Top Link1</h2>**
<p>text</p>
**<h3>Sub Link 1</h3>
<p>text</p>
<h3>Sub Link 2</h3>
<p>text</p>
<h3>Sub Link 3</h3>
<p>text</p>**

<h2>Top Link2</h2>

**Comment by ezadoo** [comment]
@rmit-hwilcox 

Have you already solved your problem?

Generally it should be fairly simple to create what you're looking for with the code I've postet above.

As I have an indicator symbol, which changes if the sub-menu is visible or not. 
As the indicator is simply made with css pseudo elements, you should be able to style the headers the same way, by simply adding a specific styling to the class on the header element.

**Comment by tscanlin** [comment]
I appreciate the further discussion and thanks for replying back on this thread @ezadoo! 
Could the absence of the `is-collapsed` class be used for this styling? something like `:not(.iscollpased)`?

**Comment by ezadoo** [comment]
I haven't thought about this possibility, but yes you're absolutely right, that should work fine too.

If you apply the `text-transform: uppercase` to the elements which gets the class `is-collapsed` added with the `:not()` pseudo element, the result should be the same.

I don't think another example is necessary, as the implementation should be pretty forward and also simpler than my idea above.

I just had my codepen 'laying around' so I didn't want to introduce an additional class.

**Comment by tscanlin** [comment]
Cool, thanks for the discussion. Since we have a way to handle this I'm going to close out this issue.

**Comment by stenzengel** [comment]
If somebody looks for an alternative solution:
The support for the `:has()-selector` is now good enough (https://caniuse.com/css-has) for my use case. For my styling (e.g., font size) I used:

```css
.toc-link::before {
	background-color: unset;
	position: unset;
	display: unset;
}

.toc-link:has(+ .is-collapsible)::before {
	font-size: 10px;
	margin-left: -12px;
	margin-right: 2px;
}

.toc-link:has(+ .is-collapsible.is-collapsed)::before {
	color: green;
	content: "▷";
	vertical-align: text-top;
}

.toc-link:has(+ .is-collapsible:not(.is-collapsed))::before {
	color: #ba3925;
	content: "▽";
}
```
