### ISSUE TITLE
How to remove .is-active-link while it's scrolled to the top with no header?

### ISSUE THREAD

**Issue by starkshaw** [tscanlin/tocbot#217]
Hi Team,

I'm building a website based on [this demo site](https://siricee.github.io/hexo-theme-Chic/2019/06/05/backreview_hexo_theme_Chic/), which in turn uses tocbot.

I'm having an issue with tocbot, which can also be found in the link above. The first heading "纵向比较" is selected when the viewer is at the very top of the page, where there is no heading. My situation is just like this, but with much more content on the top of the body text before the first heading. On a regular computer screen, I would scroll down the whole page to see the first heading. In this case, while I'm on top, the first heading remain active. This renders the TOC not entirely accurate, as the viewer is not technically on the highlighted section.

I wonder if there's a way to remove the `.is-active.link` class while I'm on the top of the article, and it only become active when I reach the first heading?

Thanks.

**Comment by tscanlin** [comment]
That is a good question. This isn't something that I had really thought of before but is an interesting use case so thanks for bringing this up.

This isn't really officially supported. However, if you know the size of your header, you could essentially just use the fixed sidebar option w/ the offset to get a class that you could use to hide the indicator at a certain scroll height. Additionally, I'd also be open to accepting a PR to add this functionality in a more official way if you have time for it.

**Comment by starkshaw** [comment]
Hi,

Unfortunately, I am not that well-versed on the frontend side, especially JavaScript...

My currently rudimentary solution is adding an invisible heading at the beginning of the body text:

```
<h5 class="invisible-heading"></h5>
```

Then, in CSS make it invisible and remove padding:

```
.invisible-heading {
    visibility: hidden;
    padding: 0 !important;
    z-index: -100;
}
```

This would not highlight the TOC on the first visible heading.

Previously, I tried

```
tocbot.init({
                tocSelector: '.tocbot-list',
                contentSelector: '.post-content',
                headingSelector: 'h1, h2, h3, h4, h5',
                collapseDepth: 3,
                orderedList: false,
                scrollSmooth: true,
                fixedSidebarOffset: '1000px',
                positionFixedClass: 'node-name--H2'
            })
```

But it seems not doing anything.

**Comment by tscanlin** [comment]
I think using an invisible heading is actually a pretty good way to achieve the results you want. 👍

**Comment by tscanlin** [comment]
If more people comment that they would like this I will see if I can find time to implement it.
