### ISSUE TITLE
Long tocbot output adds undesirable whitespace at the bottom of pages

### ISSUE THREAD

**Issue by kapooramit** [tscanlin/tocbot#218]
Hi,

If needed, I will share the actual URL of the site I am working on. What is happening if the page has sufficient headings say 20 and tocbot displays them, when the user scrolls down to bottom of the page, the footer which would usually stay stuck to the bottom edge of the page would leave the bottom and adds whitespace. If I set the display to none for the tocbot when the page is loaded, it works just fine.

What might be causing this?

-Amit

**Comment by tscanlin** [comment]
Hi, I’m not too sure why this issue would be happening. Can you share the url so that I can see the problem?

**Comment by kapooramit** [comment]
@tscanlin Thanks. I have sent you an email on me@timscanlin.net to share the URLs so that you can check the issue. Please see. Thanks!!!

-Amit

**Comment by tscanlin** [comment]
Hello, I didn't get that email, I may need to check the address is working. could you try sending to tscanlin@me.com? Thanks.

**Comment by mthearne** [comment]
I'm getting something similar.  Here is the url https://a-best-recipe.webflow.io/posts/brisket

**Comment by tscanlin** [comment]
This maybe a bit different, to fix you use case you just need to add `overflow: hidden` to `.sidebar-block`

**Comment by kapooramit** [comment]
Thanks Tim. The overflow:hidden style didn't work as it made the tocbot output move away and hide when page scrolled down. But overflow:clip worked. However, it is not desirable as it will clip. As you have the URL I shared, can you see what might work?

**Comment by kapooramit** [comment]
I take my words back. It resolved the issue. It did not clip. I am referring to overflow:clip. However, now I need to see how do I handle this very-long tocbot output dynamically because the items in it post the page height hideaway and are not visible until I scroll down the page. Maybe I can add a script to detect such instances and then add collapse to tocbot and reload tocbot with new settings. Too much work! :-)

But thanks Tim. Your idea worked. Thanks a ton!

**Comment by tscanlin** [comment]
You are welcome, glad it worked! :)

**Comment by mthearne** [comment]
> This maybe a bit different, to fix you use case you just need to add `overflow: hidden` to `.sidebar-block`

That worked perfectly. Thank you.  This is pretty slick.  Works well for me.
