### ISSUE TITLE
If header has sub items, keep 'is-active-link' class while scrolling though sub items

### ISSUE THREAD

**Issue by rmit-hwilcox** [tscanlin/tocbot#219]
I would also very much like to  know how to do this... Is it possible somehow??? I basically want the top level header to stay highlighted while the sub menu items get scrolled through... with the below code... I would want 'Top Link1' to keep its 'is-active-link' class until 'Sub Link 3' has scrolled off the windows / 'Top Link2' has started.... I hope that makes sense
```

**<h2>Top Link1</h2>**
<p>text</p>
**<h3>Sub Link 1</h3>
<p>text</p>
<h3>Sub Link 2</h3>
<p>text</p>
<h3>Sub Link 3</h3>
<p>text</p>**

<h2>Top Link2</h2>

```

**Comment by tscanlin** [comment]
currently the is-collapsed class is removed from parent items with active children. You should be able to achieve the styling you want by using that, maybe with a `:not()` too. Anyway, hope that helps!

Please provide a screenshot or PR to describe what you'd like so I can provide better advice and better understand what you want. Thanks for showing interest in tocbot!
