### ISSUE TITLE
Script initialization question

### ISSUE THREAD

**Issue by Serdaro** [tscanlin/tocbot#22]
Hello,
I am trying to apply Tocbot to my company's documentation project. In the ReadMe, the initialization is shown as below: 

```
tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.js-toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '.js-toc-content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h1, h2, h3',
});
```

As I assume, the `js-toc` should be the nav ID of my TOC, and the `js-toc-content` should be the div ID of my content. Am I thinking correctly?

Thank you.

**Comment by tscanlin** [comment]
Those are actually CSS selectors and since they start with a `.` it means they are for classes. So you can have `<div class="js-toc-content">...</div>` for your content div for example. Does that make sense? Hopefully that helps.

**Comment by Serdaro** [comment]
Thank you. So, I will use the class names of my TOC and content divs. Just hoping to validate the initialization:

```
<script>
  tocbot.init({
     tocSelector: ".toc",
     contentSelector: ".content",
     headingSelector: "h1, h2, h3",
  });
</script>
```

Is this the correct syntax? Or do I need to add the `function()` argument on top?

**Comment by tscanlin** [comment]
You have the correct initialization syntax.

**Comment by Serdaro** [comment]
Thanks a lot, it works.
