### ISSUE TITLE
How to add an class on the previous active toc-list-item element..

### ISSUE THREAD

**Issue by samjco** [tscanlin/tocbot#222]
So when an element is active is currently Title number Two, How can I get a class="`prev-active-li`" on Title Number One?

```
<li class="toc-list-item"><!-- Need new class on this element -->
    <a href="#title-1452467" class="toc-link node-name--H1 ">Title Number One</a>
</li>

<li class="toc-list-item is-active-li"> <!-- Active element -->
    <a href="#title-1452377" class="toc-link node-name--H1  is-active-link">Title Number Two</a>
</li>

```

**Comment by tscanlin** [comment]
That is currently not possible. Can you describe your use case a bit more and/or link me to an example?

**Comment by samjco** [comment]
Well, I was hoping there was a way I can add "prev-active-li" somehow to the before element.
I am trying to keep the focus on the Active link in an element of height 200px;

**Comment by tscanlin** [comment]
What are you trying to achieve with having that class? Can you show a picture or example? I don't think I really understand the use case and I've never heard the request before so I may just wait on this to see if there is more interest later. Unless you'd care to implement it yourself, I'd be open to seeing a PR for this.

**Comment by samjco** [comment]
Ok. Right now this is how I have my tocbot element showing:

![image](https://user-images.githubusercontent.com/3359062/106553743-967a1580-64df-11eb-9dfc-042a844cd835.png)

The active-li (in bold) always stays at the top... 
But I want it to stay in the center.. To achieve this, I need a class to be dynamically added to the last previously active <li>.
Make sense?

**Comment by tscanlin** [comment]
I'm sorry but I'm still not sure I understand how this will be used. Would you care to implement the desired functionality in a Pull Request so that I can review it?
