### ISSUE TITLE
mobile or narrow collapsable guidance?

### ISSUE THREAD

**Issue by ricopicone** [tscanlin/tocbot#226]
I'm seeking guidance on how to use css/js to move my nice tocbot TOC into a collapsing menu for small screens. Guidance and examples are very welcome!

(Sorry this isn't really an issue, proper. Also, great project and thanks!)

**Comment by tscanlin** [comment]
Hey! Glad you like the project. The documentation site for this project should have that behavior so you could borrow CSS from there:
http://tscanlin.github.io/tocbot/

Do you have an example site hosted somewhere so I can see where you are getting stuck?

**Comment by ricopicone** [comment]
Thanks! I have a good start on it with that help now. Once I get it in shape I'll post it back here. Thanks again!
