### ISSUE TITLE
No ID is added to headlines within the content

### ISSUE THREAD

**Issue by matteoFeduzi** [tscanlin/tocbot#232]
Hi,

unfortunately TOCBOT does not work on one site, while on the other sites I manage it works correctly.

The site in question doesn't have anything in particular. It's built with WordPress and has about ten standard plugins and that don't seem to generate any JS errors in the console.

The TOC is generated, but unfortunately it doesn't return to the various headline IDs.

How can I fix this? This is a page from the site in question where you can see the problem:
https://fantabettiamo.com/come-vincere-matematicamente-scommesse-sul-calcio/

Thank you.

**Comment by matteoFeduzi** [comment]
Solved using the code found here:
https://github.com/tscanlin/tocbot/blob/master/src/utils/make-ids.js

I thought the TOC code automatically generated the various IDs as well. Perhaps it would be helpful to include it directly.

**Comment by tscanlin** [comment]
Glad you figured out how to solve this. I will consider adding this in directly as it does seem popular.

Thanks for the feedback / suggestion!
