### ISSUE TITLE
Is there an option to remove numbering from the table of contents?

### ISSUE THREAD

**Issue by rayanamukami** [tscanlin/tocbot#235]
Thank you very much for sharing tocbot, I very much like the look, functionality and speed of it as we scroll down the index highlights the section we're currently at.

I tried to implement tocbot on one webpage [here](https://lilycalla.com/index.html), by including the `docinfo.html`, `docinfo-footer.html`, setting `:docinfo: shared,footer` at the top and including the script within a pass-through block at the bottom of the ([.adoc file](https://lilycalla.com/index.adoc)) before compiling and this resulted for me into a _numbered_ toc at the left side (with 1. 2. 3. ... before the section title).
While I do agree and that the numbers can be useful for long(er) pages, I was also wondering if there's an option to remove these numbers all-together, esp. for shorter webpages (i.e. just having the titles listed; in my example 'Year 2020' instead of '1. Year 2020').

Screenshots
![non-numbered toc](https://lilycalla.com/shinju/photo/toc-non-numbered.png)
![numbered toc](https://lilycalla.com/shinju/photo/toc-numbered.png)

**Comment by tscanlin** [comment]
Hello! This should be possible with custom CSS (via [list-style-type](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) ) or with tocbot via the `orderedList: false` option. Let me know if this is still an issue after you try those things.

**Comment by rayanamukami** [comment]
@tscanlin 
Thanks for your quick response! Could you please help also tell me where and in which CSS file or tocbot configuration i would have to insert said code?

I think it'd be nice to be able to set it in the CSS, but I'm not entirely sure where I would have to insert `list-style-type: none;`?
Would that be in the `docinfo.html`' <style> section or in the actual asciidoctor css file?
I tried putting it in asiidoctor.css file between the brackets, but it doesn't seem to take effect.

I'm also not sure how I would set the option using tocbot's API with `orderedList: false`?
As I've also tried setting the option in the index.adoc's header section  as `:orderedList: none` but the numbers are still being generated.

**Comment by tscanlin** [comment]
Hey, looking at it a bit more I think I see the issue.
Where you have the `js-toc` class, can you also try adding `toc` so it would be: `js-toc toc`

Then I just think you will need to include the CSS and it should work for you.
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.11.1/tocbot.css">`

Let me know if that doesn't work.

**Comment by rayanamukami** [comment]
Thank you for looking further into it. <3

* In [docinfo-footer.html](https://lilycalla.com/docinfo-footer.html) I added `js-toc toc` to this line

`newtoc.setAttribute('class', 'js-toc', 'toc');`

* In [index.adoc](https://lilycalla.com/index.adoc) there is already a pass-through block at the bottom of the document:

```
++++
<script src="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.11.1/tocbot.min.js"></script>
++++
```

~ I'm not sure if these are the locations you meant for the lines to be put in as the [result](url) stays the same for me once the page has fully loaded?

----

1. Just to verify that I have implemented it accordingly, it is correct to place both the `docinfo.html` and `docinfo-footer.html in the root directory.

2. And before compiling, to place in the [index.adoc](https://lilycalla.com/index.adoc) `:docinfo: shared,footer` at the top of this document and at the bottom of the document:
````
++++
<script src="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.11.1/tocbot.min.js"></script>
++++
````

3. In addition to placing `js-toc` next to `toc` in [docinfo-footer.html](https://lilycalla.com/docinfo-footer.html):
`newtoc.setAttribute('class', 'js-toc', 'toc');`

**Comment by tscanlin** [comment]
That is the JS file, but last I check you had not added the css file:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.11.1/tocbot.css">
```

**Comment by rayanamukami** [comment]
Ooh thanks for pointing out that I hadn't included the `tocbot.css`!

The toc has now indeed been indented backwards and there appear to be dots preceding the titles within the toc.

![](http://lilycalla.com/shinju/photo/toc-dot.png)

**Comment by tscanlin** [comment]
I think you may just need to change this to: `newtoc.setAttribute('class', 'js-toc toc')`

**Comment by tscanlin** [comment]
let me know if you still have issues though. And glad that helped!

**Comment by rayanamukami** [comment]
Yes! It is perfect now. <3

Thank you very much for the walk-through and sorry for all the trouble. :|

![](http://lilycalla.com/shinju/photo/toc-perfect.png)

**Comment by tscanlin** [comment]
Glad that fixed it for you!
