### ISSUE TITLE
Ideas on how to handle a conditional sticky header?

### ISSUE THREAD

**Issue by davereid-pfg** [tscanlin/tocbot#237]
We have a sticky header enabled for only certain viewports (tablet/desktop, but not mobile) so we want to use the headingsOffset configuration, but not all the time. Any advice on how to handle this would be welcome.

**Comment by tscanlin** [comment]
You should be able to use a CSS selector to determine when to handle the fixed header.
See: https://github.com/tscanlin/tocbot#fixed-headers

Do you have an example somewhere?

**Comment by sourabhbhaleraoPFG** [comment]
Can you please provide example how we can use CSS selector to add conditionaly fixed header offset setting only for desktop/tablet and not on mobile.

**Comment by tscanlin** [comment]
Yes I can as long as you can link me to an example site somewhere so I can know what css would be needed.
