### ISSUE TITLE
smooth scroll fail when anchor id use escaped(encoded) characters

### ISSUE THREAD

**Issue by Neutree** [tscanlin/tocbot#238]
[html_test.zip](https://github.com/tscanlin/tocbot/files/6999728/html_test.zip)
(This file is test case)

When use English and Chinese characters， it's ok, e.g.
```html
<h2 id="hello">hello</h2>
<h2 id="代码输出-显示图片">代码输出 显示图片</h2>
<h2 id="&#21021;&#23398;&#32773;&#30340; TensorFlow 3.0 &#25945;&#31243;">&#21021;&#23398;&#32773;&#30340; TensorFlow 3.0 &#25945;&#31243;</h2>
```

but with escaped characters(can convert [here](https://www.urlencoder.org/) `初学者` to `%E5%88%9D%E5%AD%A6%E8%80%85` for example), smooth scroll will fail, it's bug or usage error? Thanks！

```html
<h2 id="%E5%88%9D%E5%AD%A6%E8%80%85%E7%9A%84-TensorFlow-100.1-%E6%95%99%E7%A8%8B">&#21021;&#23398;&#32773;&#30340; TensorFlow 100.1 &#25945;&#31243;</h2>
```

When set `scrollSmooth` to `false`, bug disappeared

**Comment by tscanlin** [comment]
Hi and thanks for opening the issue! Others may run into this as well but I am probably a bit less likely to, so raising this issue is very helpful for all users of tocbot. Thank you! :)

Here is a PR that should fix this bug: https://github.com/tscanlin/tocbot/pull/240

**Comment by Neutree** [comment]
Thanks！ I tried this fix, it works perfectly now!
