### ISSUE TITLE
I encounter a problem with using tocbot on my project

### ISSUE THREAD

**Issue by 275761919** [tscanlin/tocbot#25]
my subtiltle tag is like:
```html
<h3 id="Emacs"><a href="#Emacs" class="headerlink" title="Emacs"></a>Emacs</h3>
```
and generated table of contents is:
```html
<li class="toc-list-item"><a data-scroll="" href="#Emacs" class="toc-link node-name--H3 ">
<a href="#Emacs" class="headerlink" title="Emacs"></a>Emacs</a>
</li>
```
It doesn't work on this situation!
If I click one or other toc list item, the web page will scroll to the top. 
There is my initialization:
```js
tocbot.init({
      // Where to render the table of contents.
      tocSelector: '#toc',
      // Where to grab the headings to build the table of contents.
      contentSelector: '.article-content',
      // Which headings to grab inside of the contentSelector element.
      headingSelector: 'h2, h3',
      collapsibleClass: 'is-collapsible',
      smoothScrollOptions: {
        easing: 'easeInOutCubic',
        //offset: 0,
        speed: 300, // animation duration.
        updateURL: false
      },
      listClass: 'toc-list',
      headingsOffset: 0,
      includeHtml: true
    });
```
Through I setup the 'updateURL' false, the URL is still changing with my clicking toc.
Is there a problem?

**Comment by tscanlin** [comment]
Is there a webpage where you can show me an example of this problem?

**Comment by 275761919** [comment]
For instance:
https://www.ctaoist.com/2016/hello-world.html

**Comment by tscanlin** [comment]
Thanks for the example.

There's a couple things going on here.

1. You are initializing tocbot too early. Yout have:

```
<!-- <script src="//cdn.bootcss.com/tocbot/2.1.5/tocbot.min.js"></script> -->
<script src="/js/tocbot.min.js"></script>
<script src="/js/main.js"></script>
<!-- <link rel="stylesheet" href="//cdn.bootcss.com/tocbot/2.1.5/tocbot.css"> -->

<body>
...
```

So you are trying to initialize tocbot before all the content on the page is ready. Try moving the script to just above the closing body tag `</body>` after all of your html content.

2. Apparently the updateURL option in smooth-scroll doesn't work and was removed. I'll update my docs to reflect this. See https://github.com/cferdinandi/smooth-scroll/commit/d4afd9f40c917b38d4ec867fc2af41acb2295e6e

Hope that helps. Let me know if you still have issues.

**Comment by 275761919** [comment]
Thanks for your help very much!
But the problem still exits after I move the tocbot.js and initialization script to the below of the `</body>` .
And I have updated the web page for example.

**Comment by tscanlin** [comment]
Thanks. Can you try disabling other scripts on the page to see if they are interfering?

**Comment by tscanlin** [comment]
Hey, did you try disabling other scripts on the page to see if they were interfering? Let me know if you still need help with this issue.
