### ISSUE TITLE
Destroy tocbot after tocSelector component has unmounted

### ISSUE THREAD

**Issue by kaitlynkatz** [tscanlin/tocbot#257]
Hello,

My team is using the tocbot library on our site (frontend built with Vue) and it works great! The main problem we keep running into is the console warnings when we try to call `tocbot.destroy()` after the toc component has already been unmounted/destroyed. The warning comes from [these lines](https://github.com/tscanlin/tocbot/blob/15604a0b21b95f44ab3836a8d83b7eb89d276df8/src/js/index.js#L88-L95).

I've tried using Vue to destroy tocbot right _before_ the toc component gets unmounted, but unfortunately with Vue 2 we only have access to a `beforeDestroy` method, and by the time that is called, the toc component is already gone.

Honestly, I don't really see the need to send a warning here- the most important part of the `destroy` method is removing the event listeners, which already does nothing if the event listener in question doesn't exist, so if there's no toc component I would expect it to just ignore the line that clears it or fail silently. Or if the warning is helpful to some, then there could be an option in the config to enable/disable it.

Any thoughts on this? I've spent a lot of time trying to get rid of this warning on my side with no success so it'd be great to resolve the issue here where it could help others too!

**Comment by tscanlin** [comment]
Hey, thanks for bringing this up! Is there a reason the warning is harmful?

I'd be open to a PR that just removes it if you have the time, I don't think its a particularly useful warning either.

**Comment by kaitlynkatz** [comment]
Eh, it's not particularly "harmful", but generally we want to avoid any console output in production (unless it's strictly necessary, but that's rare). And especially on a single-page app, if the user spends a decent chunk of time navigating through the site, they'll end up with dozens of unnecessary warnings.

I can try my hand at a PR, it doesn't seem complicated- I'll just change the try/catch format into a conditional that checks if the element exists. If I run into issues I'll come back to this thread. And thanks for the quick response!

**Comment by kaitlynkatz** [comment]
Okay, PR created. Feel free to take it over and publish if you approve it, I'm not very familiar with the publishing process for npm packages

**Comment by tscanlin** [comment]
Thanks for the PR! I've merged it and your fix is released in `tocbot@4.17.2`

If anything else comes up please let me know. Thank you!!
