### ISSUE TITLE
Save the scroll #hash position on page refresh

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [tscanlin/tocbot#258]
The test: Click on anchor - than refresh the page (The page jump to top). 
https://cdpn.io/ezra_siton/debug/eYGZayz/dGrXWjQnYqEM#italy

Their is some option related to this? (50% of the times it works and 50% not).

**Comment by tscanlin** [comment]
Hmm, that link is not working for me. This usually happens because of script loading / execution order. Maybe wrap in DOM load?

**Comment by Ezra-Siton-UIX** [comment]
Thanks. The issue solved (It was some cache issue!) Thanks
