### ISSUE TITLE
Scrolling problem with large TOCs

### ISSUE THREAD

**Issue by owenh000** [tscanlin/tocbot#27]
The scrolling fails with large TOCs: the list continues beyond the lower scroll limit.

For example, run the following command and paste the result into the "Try it" Markdown tester on <https://tscanlin.github.io/tocbot/>. (Warning: the `xclip` command will write to your clipboard.)

```
i=0; while [ $i -lt 50 ]; do [ $i = 0 ] && echo "# top"; i=$(($i + 1)); echo "## section $i"; done | xclip -selection clipboard
```

Thanks!

**Comment by owenh000** [comment]
The following command adds three trailing top-level headings. This further exhibits the behavior, you can now see that the list of level 2 sections is truncated. (Warning again: the `xclip` command will write to your clipboard.)

```
i=0; while [ $i -lt 50 ]; do [ $i = 0 ] && echo "# part1"; i=$(($i + 1)); echo "## section $i"; [ $i = 50 ] && echo -e "# part2\n# part3\n# part4"; done | xclip -selection clipboard
```

**Comment by tscanlin** [comment]
I think this is because of the max-height limit in CSS.

You should be able to adjust this style:

```
.is-collapsible {
  max-height: 1000px;
  overflow: hidden;
  transition: all 300ms ease-in-out;
}
```

By simply overriding the max-height value with a value that makes sense for your use case

```
.is-collapsible {
  max-height: 3000px;
}
```

Note that this may make the open / close animation less smooth since the max-height is larger.

**Comment by owenh000** [comment]
That fixes it. Thank you for your quick reply!
