### ISSUE TITLE
Flash when scrolling / doesn't scroll to right spot

### ISSUE THREAD

**Issue by kareem** [tscanlin/tocbot#273]
I've noticed two issues with tocbot that seem unusual:
1. The TOC flashes when I click on a link (maybe like the TOC is being redrawn)
2. The document doesn't always scroll to the right place on page unless I click the link twice

Here's a video:
https://www.dropbox.com/s/e2zl8jd3srg4qns/screencast%202022-02-21%2022-05-56.mp4?dl=0

Code:

```
tocbot.init({
    tocSelector: '.js-toc-list',
    contentSelector: '.js-toc-content',
    headingSelector: 'h2',
    hasInnerContainers: false,
    ignoreSelector: '.js-no-anchor',
    orderedList: false,
    headingsOffset: 70,
    scrollSmoothOffset: -70,
});
```

I've read the docs and scoured closed issues and can't find anything that looks like a promising fix.  Feels like I'm doing something wrong here / missing something.  

Thanks in advance!

**Comment by kareem** [comment]
Solved the flashing-while-scrolling issue by removing a lingering `smooth-scroll` style from my CSS:
```
<style>
    html {
      scroll-behavior: smooth;
    }
</style>
```

Fixed the "The document doesn't always scroll to the right place on page unless I click the link twice" issue.  Here's how:

* I am using [jquery-anchorify](https://github.com/Automattic/jquery-anchorify) to turn headings into anchors.  * After reading [this comment](https://github.com/tscanlin/tocbot/issues/254#issuecomment-991802525) I suspected tocbot was building the TOC before anchorify was done anchoring links
* I verified this by running `tocbot.refresh()` in the console after all JS was done executing
* After running `tocbot.refresh()`, there was never an issue with scroll offset - it always worked on the first click

The solution is to put the tocbot init code in a function, and pass that function as a callback to another that runs anchorify:
```
      $(document).ready(function() {

          function initAnchors(callback) {
            jQuery('.blog').anchorify();
            callback();
          }

          function initTocbot() {
            tocbot.init({
              // Where to render the table of contents.
              tocSelector: '.js-toc-list',
              // Where to grab the headings to build the table of contents.
              contentSelector: '.js-toc-content',
              // Which headings to grab inside of the contentSelector element.
              headingSelector: 'h2',
              // For headings inside relative or absolute positioned containers within content.
              ignoreSelector: '.js-no-anchor',
              orderedList: false,
              headingsOffset: 70,
              scrollSmoothOffset: -70,
            });
            tocbot.refresh();
          }

          initAnchors(initTocbot);
      });
```

**Comment by tscanlin** [comment]
Glad you were able to figure this out! Thanks for sharing.

**Comment by kapooramit** [comment]
I was facing the same issue today. Nothing worked for me. I use anchorjs and thought it was doing something but no. After trying everything else, I ended up doing this - not neat but works unless user races to click a heading in tocbot within 1second after the page is loaded.

````
setTimeout(function(){
        tocbot.refresh();
        //console.log("tocbot refreshed);
       }, 1000);
````

**Comment by murtuzaalisurti** [comment]
@tscanlin @kareem the scroll behavior of smooth when enabled in `tocbot` conflicts with the CSS variable already defined in the CSS file (if any). I was able to resolve the jittery experience by disabling smooth scroll behavior in `tocbot` and just keeping a global CSS style prop.

**Comment by tscanlin** [comment]
@murtuzaalisurti  Can you share a reproduction of this issue? I'm not seeing this when I test on the docs site. Also, which browser are you using? Thanks!

**Comment by murtuzaalisurti** [comment]
@tscanlin to reproduce it, turn on the `scrollSmooth` prop in tocbot and add a global CSS scroll behavior smooth prop
```
html:focus-within {
    scroll-behavior: smooth;
}
```

sometimes, when you click on an anchor link, it looks like the browser is trying to decide the pacing of the scroll. It goes up and down a bit before actually scrolling to the link.

https://github.com/user-attachments/assets/425e3674-bd98-40a9-87bd-ac6487ca92f7

**Comment by tscanlin** [comment]
So maybe the best fix is to just add some info about this to the readme?
Saying to disable tocbot smoothScroll if you have the CSS property added instead so that they don't conflict?
I'll need to test the browser way some more to make sure it handles edge cases the same way. Thanks for bringing this up though!
Does that sound ok to you @murtuzaalisurti? Or do you think there is a better way to solve this?

**Comment by murtuzaalisurti** [comment]
@tscanlin I think that's a good idea to add it to the docs for now. I can add it.

**Comment by tscanlin** [comment]
Yes, the docs would just be the readme file. That would be great, thanks!!

**Comment by ztf-git** [comment]
const contentDoc = document.getElementById('markdown-view')
      const menuNodes = contentDoc .querySelectorAll('h1,h2,h3')
      Promise.all(Array.from(menuNodes).map(h => {
        const textContet = h.textContent
        h.id = md5(textContet)
        return h
      })).then(() => {
        const scrollElement = document.getElementById('md_main_container')
        const firstH1 = document.querySelector(`#${this.id} h1`)
        const hashId = '#' + firstH1?.id || ''
        tocbot.init({
          tocSelector: '#tocify',
          contentSelector: '#' + this.id,
          headingSelector: 'h1, h2, h3',
          hasInnerContainers: true,
          collapseDepth: 3,
          activeListItemClass: 'is-active-li',
          // 🔧 核心修复：监听点击事件
          onClick: function(e) {
            setTimeout(() => {
              const offsetTop = 200
              const scrollTop = scrollElement.scrollTop - offsetTop
              if (window.location.hash === hashId) {
                scrollElement.scrollTo({ top: 0, behavior: 'smooth' })
              } else {
                scrollElement.scrollTo({ top: scrollTop, behavior: 'smooth' })
              }
            }, 0)
          }
        })
      })
