### ISSUE TITLE
On complete callback

### ISSUE THREAD

**Issue by thom801** [tscanlin/tocbot#278]
Hey sorry if this is documented somewhere else but I did search around all issues etc.

What I need is just a way to check if the `Tocbot.init()` method actually found any headings after initialization. The issue I'm having is I have articles on our blog where there are actually no headings so then I have a blank area in my layout that has no content and needs to be hidden if no headings were found. 

Let me know if there is some way I can do this. Thank you!

**Comment by tscanlin** [comment]
This is better handled on the server side but you could just use document.querySelector to check that the headings exist and then initiate Tocbot after that. Currently there is no built in way to do this.
