### ISSUE TITLE
Body { overflow: hidden; } vs. Dynamic highlight

### ISSUE THREAD

**Issue by mikenils** [tscanlin/tocbot#28]
Hi, Tim! Thank you very much for Tocbot, looks very interesting!

I have a layout with 2 columns - left column for TOC and right column for main content. Quite common approach.

Each column have it's own scrollbar (`overflow: auto`), while the body itself is not scrollable
(`body { overflow: hidden; }`).

(This way, each column could be scrolled independently of another.)

And, my problem is that Tocbot doesn't work in this case. TOC is shown, but despite of scrolling, it always highlight only the first header.

Here is code which I tested:
https://jsfiddle.net/opbkpvwj/

**Comment by tscanlin** [comment]
Tocbot does require that the body element be scrollable for it to work.

For the layout you described couldn't you make the sidebar `position: fixed; overflow-y: auto;` and keep the body scrollable to get the same effect of two scrollable panels?

**Comment by mikenils** [comment]
In this case, if TOC is large, when I scroll it, it is easy to accidentally scroll the body too. In other words, I wanted just to scroll the TOC, but I also scrolled "pages" of my document.

In contrast, while I scroll TOC, I want to be sure, that the main column will stay at it's place. If you have 30-40 headings in document, it's worth it.

By the way, the approach I use I firstly seen in Chrome bookmark manager.

**Comment by tscanlin** [comment]
Making `overflow: hidden` causes issues with the smooth-scroll library. See their README under the Known Issues section for more details (https://github.com/cferdinandi/smooth-scroll#body-styling). But I should probably include this info in the Tocobot readme as well.

However if you make the body scrollable and just want to prevent the sidebar from causing the page to scroll when its at the top or bottom check out this stackoverflow post for a workaround: http://stackoverflow.com/questions/5802467/prevent-scrolling-of-parent-element

Hope that helps.

**Comment by mikenils** [comment]
Thank you for link, now I use it, instead of my previous method.

**Comment by tscanlin** [comment]
Awesome, glad to hear that works for you! Thanks for showing an interest in Tocbot as well :). I hope it works well for your use case, feel free to reply back here if you have any more questions.

Happy coding!
