### ISSUE TITLE
List generation with non-sequential heading levels

### ISSUE THREAD

**Issue by zmoon** [tscanlin/tocbot#280]
For example, h1 with multiple h3 children without h2 in between. The first h3 gets treated as separate from the others, as if it were an h2, i.e., it goes in a separate list,  although they all have the `node-name--H3` class.

Here is an example: <https://jsfiddle.net/wjLrsft8/2/>

**Comment by tscanlin** [comment]
Hey, thanks for reporting this issue and sharing the example! And sorry I've been late to respond, I got sick with Covid over the weekend. I'll try to look into this tonight and see what I find.

**Comment by tscanlin** [comment]
I took the same content that you had and put it in the documentation site and it seems like it has the proper nesting there. I'm not quite sure what is causing this issue.

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5033032/175448459-800fa91b-ac55-42fd-9d77-40301a4a4fff.png">

**Comment by zmoon** [comment]
I think the version I was using was old and it has been fixed since then. I was using the version from the readme.

With a more current version it works in my example: <https://jsfiddle.net/vuqdt9zx/>

**Comment by tscanlin** [comment]
Awesome, glad the latest version fixed this issue! I’ll work on updating the readme version.

**Comment by zmoon** [comment]
I think that would help lazy people like me who just copy the readme snippets. Also I was thrown off because 4.12.0 is the latest GitHub "release" (though I now see there are many more recent tagged versions).

**Comment by zmoon** [comment]
For the latter point a little badge at the top like this could be cool.

![cdnjs](https://img.shields.io/cdnjs/v/tocbot)

**Comment by tscanlin** [comment]
Thanks for the great suggestion! I've added the badge in this PR: https://github.com/tscanlin/tocbot/pull/282
