### ISSUE TITLE
How to use for WordPress?

### ISSUE THREAD

**Issue by oldbooklover** [tscanlin/tocbot#284]
It works very nice, light and fast
How to use for WordPress?

will be appreciated

**Comment by tscanlin** [comment]
Hello! There is no officially supported wordpress plugin for tocbot at this time unfortunately. However, from a quick google search it looks like there are a couple of popular themes that support it / have tutorials, see:
https://designody.com/table-of-contents-using-tocbot-in-genesis/
https://wpdevdesign.com/automatic-table-of-contents-using-tocbot-in-oxygen/

Hope that helps!
