### ISSUE TITLE
Unusual issue with .is-active-link when there are multiple tocbots on a page

### ISSUE THREAD

**Issue by mmmmyo** [tscanlin/tocbot#298]
hello. Thanks for making such a great plugin.
I'm sorry for asking questions because I don't seem to understand the manual well because I'm not good at English.

There is a problem that .is-active-link does not change properly when multiple tocbots are applied to one page.
can you help me solve this problem?

This is an example page.
https://jsfiddle.net/sweetmyo/8m6Lh0c9/

**Comment by tscanlin** [comment]
Currently having multiple instances of tocbot is not supported on one page.
