### ISSUE TITLE
the icon should stay original position when toc unfold

### ISSUE THREAD

**Issue by pheotry** [tscanlin/tocbot#303]

**Comment by tscanlin** [comment]
Can you please provide an example of this via a link? I'm not sure what you mean.

**Comment by pheotry** [comment]
> Hello! Can you please provide an example of this via a link? I'm not sure what you mean.

when it unfold, it should look like this

![image](https://user-images.githubusercontent.com/43376740/229326645-78ae7d46-c524-4a04-bb83-f4fd7eec0472.png)

**Comment by tscanlin** [comment]
Hmm, I don't see that. Do you have a link or steps to reproduce the issue?

**Comment by pheotry** [comment]
> Hmm, I don't see that. Do you have a link or steps to reproduce the issue?

I mean that the hammer icon to the right will be more convenient

**Comment by tscanlin** [comment]
I'm sorry, I'm not really sure what the issue is or how to reproduce the issue you are seeing. Can you provide any more details and steps to reproduce this?

**Comment by tscanlin** [comment]
What hammer, I don't see a hammer?
