### ISSUE TITLE
can't work on hexo-theme-landscape

### ISSUE THREAD

**Issue by embedBook** [tscanlin/tocbot#305]
I have add one div block in my html, looks like this:

<div class="js-toc-inner"> 
      <ol id="js-toc"></ol>
</div>

**Comment by tscanlin** [comment]
You may need to wrap in a code block for html to show up. But a link to a website that reproduces this issue would be very helpful.

**Comment by embedBook** [comment]
> You may need to wrap in a code block for html to show up. But a link to a website that reproduces this issue would be very helpful.

Not effect!!
add div block, <div class="js-toc"> </div>

**Comment by embedBook** [comment]
> You may need to wrap in a code block for html to show up. But a link to a website that reproduces this issue would be very helpful.

only local wetsite ! maybe css  Settings are inappropriate！or how tocbot init function work?

**Comment by tscanlin** [comment]
Can you please post an example reproducing this issue? Otherwise I'm not sure how I can help.

**Comment by embedBook** [comment]
resolved!

**Comment by embedBook** [comment]
resolved!
