### ISSUE TITLE
tocbot 4.18.2 is not detecting h3

### ISSUE THREAD

**Issue by ppazos** [tscanlin/tocbot#306]
I have headingSelector: 'h1, h2, h3' and it detects h1 and h2 but not h3.

**Comment by ppazos** [comment]
Sorry, the items are there but are hidden, only shown when I scroll to the parent h2 section, how can I display the h3 by default?

**Comment by ppazos** [comment]
Nevermind, just found the collapseDepth property that was what I needed.

**Comment by zjplab** [comment]
Add to that:

```javascript
  // How many heading levels should not be collpased.
  // For example, number 6 will show everything since
  // there are only 6 heading levels and number 0 will collpase them all.
  // The sections that are hidden will open
  // and close as you scroll to headings within them.
  collapseDepth: 6,
```
