### ISSUE TITLE
Feature: Transform to dropdown on mobile

### ISSUE THREAD

**Issue by abercrombiexo** [tscanlin/tocbot#322]
This is a fantastic little find and I just wondered if it’s possible to have an option for mobile to transform to  into a dropdown menu - unless I’ve missed something?

**Comment by tscanlin** [comment]
Hey thanks for the suggestion. You should be able to accomplish that with some custom CSS. Do you have an example site where you are trying to do this? The styling of the dropdown is kinda outside the scope of what tocbot does, but I will try to help if you can share an example.
