### ISSUE TITLE
index.d.ts mismatch current options

### ISSUE THREAD

**Issue by ibarapascal** [tscanlin/tocbot#324]
As the title, currently, the `index.d.ts` lacks the definition of 

- activeListItemClass
- tocScrollOffset

ref:

- default options: https://github.com/tscanlin/tocbot/blob/master/src/js/default-options.js
- README options: https://github.com/tscanlin/tocbot?tab=readme-ov-file#options

those two above seem aligned, but

- index.d.ts: https://github.com/tscanlin/tocbot/blob/master/index.d.ts

**Comment by tscanlin** [comment]
I can look into this with my other PR. Thanks for the heads up!

**Comment by tscanlin** [comment]
This should be updated / fixed in this PR: https://github.com/tscanlin/tocbot/pull/325
