### ISSUE TITLE
How can I add an extra nav link for example "Comments"?

### ISSUE THREAD

**Issue by bowencool** [tscanlin/tocbot#327]

**Comment by tscanlin** [comment]
The toc links are generated from the content so if you add it there it should show up. Do you have a link you can provide and more info about this issue so I can try to help?

**Comment by bowencool** [comment]
https://blog.bowen.cool/posts/how-to-forward-sms-messages-to-your-todo-list
<img width="1107" alt="image" src="https://github.com/tscanlin/tocbot/assets/20217146/f82b5c14-265e-45af-840f-b3a7003e3d1b">
The "#comments" section is outside of the article area. I would like to include an additional link there.

**Comment by tscanlin** [comment]
Can you just move the comment section under a common parent element along with the rest of the content?
