### ISSUE TITLE
Ignore header tags with no ids

### ISSUE THREAD

**Issue by sivaram10111998** [tscanlin/tocbot#331]
Currently when a new line is added which is of type header and without any text, it shows up in the toc with an empty bullet point. So can we get a way to ignore the header tags that don't have any id.
Eg: `< h1>&nbsp< /h1>`
Even though above tag don't have any content and id, it's being shown in toc.

**Comment by tscanlin** [comment]
Why are you including a heading with no content in it in the first place? Maybe there's some use case I'm missing but that wouldn't seem to be very semantic to me. Maybe it could be removed instead?
