### ISSUE TITLE
Tocbot scrolls to the right position onClick but highlighting doesn't seem to show the active section

### ISSUE THREAD

**Issue by tatiana-kushnir-89** [tscanlin/tocbot#334]
I encountered this problem and the solution from [here](https://github.com/tscanlin/tocbot/issues/145) did not help me. Are there any other possible ways to solve this bug?

**Comment by tscanlin** [comment]
Hmm, sorry to hear that. Can you please post an example somewhere that shows the issue so I can try to see what is happening?

**Comment by tatiana-kushnir-89** [comment]
can I send you a link to my test project more privately? maybe by email? In the context of my project, it will not be possible to take a separate part of code and place it

So I can send you a link to my example, and here I can attach part of my code with settings

**Comment by tscanlin** [comment]
Yeah I understand that, I emailed you. Can you also include a screenshot in your email incase I have any issues getting it setup? Thanks!

**Comment by tatiana-kushnir-89** [comment]
Tim explained that I also need the options hasInnerContainers: true, headingsOffset: 100, scrollSmoothOffset: -100, this affects the margins in the second-level lists in my case.

Thanks again to the Toсbot developer for such a useful plugin)
