### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by bashmish** [tscanlin/tocbot#337]
Do you have plans to support an ESM module output?
As `"module": "path/to/esm-file.js"` or via `exports` in package.json?

I'd be happy to work on it and discuss the best approach to keep things maximum compatible or introduce a new major if needed.

**Comment by bashmish** [comment]
Great, I'll check the post and work on this soon. The usage of `exports` might be tricky since it will block access to certain private files internally, but people might be using them, but ideally I'd like to use that as it gives simple conditional configuration for ESM and CJS.

**Comment by tscanlin** [comment]
Ok sounds good. It is only used in browsers, not in node. Yeah, hopefully the private files can be declared with:
```
"./*": {
      "require": "./dist/*.js",
      "import": "./dist/*.mjs"
}
```

But I'm not sure how that would affect deeply nested files. Anyway, I think the files in `utils` would be the main ones people import directly.

**Comment by bashmish** [comment]
I made some progress, now working on tests, hope to finish this weekend.

The files in `dist` should be exported in the same way as before, so that people who import `tocbot/dist/tocbot.js` can have a compatible update. On the root I'll export files too, but the build will be different. I was thinking of doing both CJS and ESM on the root, but if you say it's only for browsers, I can as well just remove the CJS one, which would simplify things even further, but in case someone needs a CJS one, we can add it later, it's a new entry point anyway, so should be considered a new feature then. On top of that paths like `tocbot/tocbot.js` and alike are new too, can add it if you want, but they are not currently used, so it's also a new feature then.

**Comment by bashmish** [comment]
I realised also that `./dist/tocbot.mjs` is not need and if the sources are ESM (which is required to make it work for my ESM use-cases anyway), we can as well keep the old path to `src/js/index.js` also in the exports, even for more compatibility and I think this is gonna be better when debugging the code since the sources will be just loaded in DEV mode without any compilation required, which is one of the selling point of ESM in general.
