### ISSUE TITLE
Structure changed and now index.js references non-existent src dir

### ISSUE THREAD

**Issue by jcniedfeldt2** [tscanlin/tocbot#341]
4.27.7 removed the src directory which causes the following error when trying to run Storybook on a new install:

```sh
✘ [ERROR] Could not resolve "./src/js/index-esm.js"

    node_modules/.pnpm/tocbot@4.27.7/node_modules/tocbot/index.js:1:39:
      1 │ import { destroy, init, refresh } from './src/js/index-esm.js'
```

Edit:
The files in question can be seen [here](https://www.npmjs.com/package/tocbot/v/4.27.7?activeTab=code) and the `src/` folder referenced in `index.js` is indeed not present.

**Comment by jcniedfeldt2** [comment]
Thank you for the quick updates. 4.27.12 does not produce the issue and Storybook is able to start.

**Comment by jcniedfeldt2** [comment]
Thank you for the quick updates. 4.27.12 does not produce the issue and Storybook is able to start.

**Comment by tscanlin** [comment]
Awesome, yep! Just got that version out (`tocbot@4.27.12`) you are quick! 

Thanks for picking it up so fast, verifying, and resolving this. Really appreciate it @jcniedfeldt2 👍
