### ISSUE TITLE
No more types?

### ISSUE THREAD

**Issue by TheDutchCoder** [tscanlin/tocbot#344]
tocbot doesn't seem to ship types anymore.
There's a reference in the package.json: `"types": "./index.d.ts",` but that file doesn't exist anymore.

**Comment by tscanlin** [comment]
Hey, I think I may have forgot to add that file to the files array in package.json. 
I just added it and published a release that should have it: `tocbot@4.27.19`
Can you try it out and let me know if it fixes things? Thanks for the heads up!

**Comment by tscanlin** [comment]
This should be fixed now. Please respond if you are still having issues. Thanks!
