### ISSUE TITLE
FYI: cdnjs.com reference stuck at v2.1.5

### ISSUE THREAD

**Issue by bridgeport** [tscanlin/tocbot#35]
Thanks for this fantastic script. This is just an FYI, but your cdnjs reference only goes up to v2.1.5.

https://cdnjs.com/libraries/tocbot

**Comment by tscanlin** [comment]
Hey, thanks for the heads up! I will follow up with them.

**Comment by tscanlin** [comment]
Sorry I got around to opening an issue about this pretty late, but here it is for reference: https://github.com/cdnjs/cdnjs/issues/11055

**Comment by tscanlin** [comment]
This is now fixed:
https://cdnjs.com/libraries/tocbot
