### ISSUE TITLE
Error "no default export" when using latest (4.29.0) and typescript

### ISSUE THREAD

**Issue by pacoorozco** [tscanlin/tocbot#355]
Hi!

Using the latest version (4.29.0) in a NextJs site a got this error:

```
./src/components/Layouts/DocsLayout/ToC.tsx:3:8
Type error: Module '"/home/public/src/Adevinta/YAMS/frontend-next/node_modules/tocbot/index"' has no default export.

  1 | import { useRouter } from 'next/router';
  2 | import React, { useEffect } from 'react';
> 3 | import tocbot from 'tocbot';
    |        ^
  4 |
  5 | export const ToC: React.FC = () => {
```

You can see the code of the `ToC.tsx` file, which was working well before. I have recently updates these packages:

- typescript 5.54 --> 5.6.2
- eslint-config-next 14.2.8 --> 14.2.12
- @next/eslint-plugin-next 13.2.8 --> 14.2.12
- next 14.2.8 --> 14.2.12

Thanks!

**Comment by tscanlin** [comment]
Thanks for raising this issue. I've noticed it to, but it should work if you switch to: 
`import * as tocbot from 'tocbot';`

I'll work on a fix to make it work both ways. Thanks!

**Comment by pacoorozco** [comment]
Thanks a lot @tscanlin It worked!

**Comment by tscanlin** [comment]
Now both ways should work. Thanks!
