### ISSUE TITLE
Menu resizes

### ISSUE THREAD

**Issue by SPQRInc** [tscanlin/tocbot#47]
Hello,

I got tocbot working - and it seems to work great.

But there is a little problem: The menu box resizes as shown in this gif.

![2017-05-15 09 48 20](https://cloud.githubusercontent.com/assets/23051150/26047542/e8055dc6-3953-11e7-90af-6ecbe7673351.gif)

How can I solve this?

**Comment by tscanlin** [comment]
Glad to hear you got it working! Can you link me to an example page with this issue?

My hunch is it could be related to 'box-sizing: border-box' not being set maybe?

**Comment by tscanlin** [comment]
Actually it's more likely that the toc is changing width, try throwing a `min-width` on there.

**Comment by tscanlin** [comment]
Did the min-width fix this?

**Comment by SPQRInc** [comment]
Hello @tscanlin ,

Sorry, was not working on my project yesterday. 

I think I did not understand what you meant: `min-width` is not an option in tocbot. So you mean that I should define a `min-width` in my CSS?

**Comment by tscanlin** [comment]
Yes

**Comment by tscanlin** [comment]
Does setting min-width fix this issue?
