### ISSUE TITLE
Tocbot not working with dynamically added content

### ISSUE THREAD

**Issue by giorgio79** [tscanlin/tocbot#50]
Hello,

I am displaying tocbot with dynamically added text.

It detects the headings, but the links do not work and it does not scroll. Any tips? :)

http://proofreadbot.com/ui/tocbot-demo/#

**Comment by tscanlin** [comment]
Most likely you are missing id's for the headings. I can verify tonight.

**Comment by giorgio79** [comment]
Yes, I dont have any ids for headings. I was unaware they were required.

**Comment by tscanlin** [comment]
Yeah, I do mention it in the requirements section of the readme:
https://github.com/tscanlin/tocbot#requirements

But you're not the first one to have missed it ;), maybe I'll move it up to the usage area and add a bold NOTE label to make that more clear. Would that help?

I appreciate this feedback.

**Comment by giorgio79** [comment]
Much appreciated.
