### ISSUE TITLE
zenscroll vs Bootstrap Affix

### ISSUE THREAD

**Issue by giorgio79** [tscanlin/tocbot#52]
Just learned Bootstrap has a built in scrolling capability called affix. Is zenscroll better? :)

http://getbootstrap.com/javascript/#affix

Affix demo:
https://jsfiddle.net/okiewardoyo/twkthn44/2/

**Comment by tscanlin** [comment]
Affix just seems to make the menu fixed position at a certain scroll point. This is different than zenscroll which makes the scrolling animation smooth. Tocbot has the functionality of affix by using the following options:

```
// Fixed position class to add to make sidebar fixed after scrolling
// down past the fixedSidebarOffset.
positionFixedClass: 'is-position-fixed',
// fixedSidebarOffset can be any number but by default is set
// to auto which sets the fixedSidebarOffset to the sidebar
// element's offsetTop from the top of the document on init.
fixedSidebarOffset: 'auto',
```

**Comment by giorgio79** [comment]
Tried that but no luck :)

Also, for the scrolling do I have to include zenscroll as well? Or is it included in tocbot.js?

Hmm seems not https://github.com/tscanlin/tocbot/search?utf8=%E2%9C%93&q=zenscroll&type=
Will have to do that manually :) For a moment the tut had me believe that dependency is merged into tocbot.min.js

**Comment by tscanlin** [comment]
You just need Tocbot. Zenscroll is included.

**Comment by tscanlin** [comment]
Is it ok to close this issue?

**Comment by giorgio79** [comment]
Yes, many thx!
