### ISSUE TITLE
Setting scroll offset

### ISSUE THREAD

**Issue by Adertoilop** [tscanlin/tocbot#53]
Hi, 
I hope I'm just missing something here, but shouldn't there be a setting to set an offset for the auto scroll?
"headingsOffset" works when manually scrolling, but if I click on a link in the TOC, the heading is hidden behind the fixed top navbar:

![tocbot](https://cloud.githubusercontent.com/assets/25416420/26282583/4c7f38d4-3e14-11e7-834a-80ca4111b06f.gif)

Any suggestions?

**Comment by tscanlin** [comment]
That's a great question. I've found that the best way to handle having a fixed header with tocbot is to use some custom CSS like so:

```
h1::before, h2::before, h3::before, h4::before, h5::before, h6::before {
    display: block;
    content: " ";
    height: 60px;
    margin-top: -60px;
    visibility: hidden;
}
```

Hopefully that helps.
