### ISSUE TITLE
OL wrapping element instead of UL

### ISSUE THREAD

**Issue by bridgeport** [tscanlin/tocbot#57]
Thanks for this great script. Unless I'm missing it, could you please add an option to use OL instead of UL as the list container tag (including sublists)? Thanks.

**Comment by tscanlin** [comment]
I'll consider adding this. What's your use case for using ol instead of ul?

**Comment by bridgeport** [comment]
@tscanlin Thanks for considering. Visually, I'd prefer numbers, similar to what you see here:

> https://en.wikipedia.org/wiki/Help:List
> https://codex.wordpress.org/Installing_WordPress

I realize those two references are actually using an UL tag even though they're representing their list as numeric. They could use OL and use nesting counters, as shown here:

> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters#Nesting_counters

Which would seem to be more appropriate.

Also, having the table of contents in a OL allows me to more specifically target that tag for styling, which is sometimes the only element on the page that I use that tag for.

Thanks.

**Comment by tscanlin** [comment]
Yeah, I guess the numbering you want could be easily accomplished with css. I would strongly encourage you to not style your css using element selectors. It makes your css much less portable and more brittle because you won't be able to add an ol element anywhere on the page without it getting other styles. What is wrong with using a class instead?

**Comment by tscanlin** [comment]
I don't think this option is that useful and it would add extra code complexity so I'm gonna close this.

**Comment by ksh5** [comment]
A table of contents is in a specific order correspondent to the document/article outline. Wouldn't be `<ol>` the appropriate (read: semantic) HTML Tag for this use case?

**Comment by tscanlin** [comment]
That's a good point and I think since two of you have now voiced a desire for this I'll make the change.

**Comment by tscanlin** [comment]
published `4.1.0` with this change
