### ISSUE TITLE
Prevent wrong active link

### ISSUE THREAD

**Issue by SPQRInc** [tscanlin/tocbot#59]
Hello,

at the moment the active link is not set correctly.

If I open my site the first header is selected correctly. But if I am scrolling down just a bit, it "hops" over all other headings and sets the last one as "active" (the actual heading is not even visible yet).

How can I fix that?

<img width="935" alt="bildschirmfoto 2017-07-18 um 16 51 21" src="https://user-images.githubusercontent.com/23051150/28323619-a7924c82-6bd9-11e7-94db-21ab29c8c85f.png">

**Comment by tscanlin** [comment]
Can you link me to an example URL?

**Comment by tscanlin** [comment]
Well, thanks for the link.. this took me a bit longer to diagnose than I would have liked, but I think its because you passed `headingsOffset: '0'` as a string instead of a number. Try changing that.
