### ISSUE TITLE
Cyrillic content of headers

### ISSUE THREAD

**Issue by dayfuaim** [tscanlin/tocbot#6]
TocBot doesn't work with Cyrillic, as it leaves Cyrillic anchors as just "#".

**Comment by tscanlin** [comment]
What parser are you using for markdown? When I use marked for parsing it seems to skip any Unicode characters as well. Does it work if you set the id with Cyrillic characters manually with HTML?

**Comment by tscanlin** [comment]
Since tocbot doesn't manipulate the anchors or create the ids I think this may be an issue with the markdown parser. Were you able to get it to work by manually setting the id in the HTML?

**Comment by tscanlin** [comment]
I'm going to close this, but feel free to re-open if I can help.
