### ISSUE TITLE
In the roadmap it mentioned that it needed reactJS support?

### ISSUE THREAD

**Issue by deltaskelta** [tscanlin/tocbot#62]
It mentioned that reactJS support was needed which led me to believe that it was not currently working with rectJS. I got it working pretty much effortlessly in reactJS so I was wondering what you meant by reactJS support or if that can be removed from the readme?

**Comment by tscanlin** [comment]
That todo item is a little confusing, because Tocbot works fine with react. What I meant by react support is that it could be rendered with react rather than updating he Dom directly. But I agree that it's confusing and will remove that part. Thanks for the feedback!
