### ISSUE TITLE
Option to add anchors next to header tags or wrap header tags as anchors

### ISSUE THREAD

**Issue by lei-cao** [tscanlin/tocbot#70]
Hi @tscanlin , 

thank you for this awesome tool. 

It's good if I can achieve this

`<h2 id="the-header-id"><a href="#the-header-id">About this Guide</a></h2>`

Or `<h2 id="the-header-id">About this Guide<a href="#the-header-id">&#128279;</a></h2>` with `&#128279;` configurable.

Since the id of the header is generated by tocbot, so the option to make the header tags linkable from tocbot would be nice. 

Cheers

**Comment by tscanlin** [comment]
Hi, thank you for the suggestion. However, the id of the header is actually not generated by tocbot and modifying the content is out of scope for tocbot. I would rather leave it up to authors to determine how to modify the content since there could be many different opinions about this.

**Comment by lei-cao** [comment]
ah yes! you are right. Thanks @tscanlin
