### ISSUE TITLE
IE10 compatibility when using via NPM

### ISSUE THREAD

**Issue by TomiTakussaari** [tscanlin/tocbot#72]
Hi

I am using Tocbot in [Gatsby](https://www.gatsbyjs.org/) site like this:

```javascript

import Tocbot from "tocbot";

export class Component extends Component {
    componentDidMount() {
        Tocbot.init({
            tocSelector: "#toc",
            contentSelector: "#content",
            headingSelector: "h1, h2, h3",
            scrollSmooth: false
        });
    }

    componentDidUpdate() {
        Tocbot.refresh();
    }

    componentWillUnmount() {
        Tocbot.destroy();
    }
```

Problem is that this fails in IE10, because [scrollsmooth uses const declarations](https://github.com/tscanlin/tocbot/blob/master/src/js/scroll-smooth/index.js#L8), which do not work in IE<11.

It seems to be only place in Tocbot to use const declarations, so perhaps its an accident ?

http://tscanlin.github.io/tocbot/ does seem to work in IE10, so apparently code running there is babelized somehow ?

Strange thing is that that this is not fixed in Gatsby's build process, perhaps I have to investigate that further.

**Comment by tscanlin** [comment]
Probably doesn't go through babel because gatsby is ignoring node_modules?

But I just pushed a commit to change the const declarations to var to fix IE. Try using `tocbot@4.0.1`

**Comment by TomiTakussaari** [comment]
Yeah, 4.0.1 fixed it on IE.

Thanks for quick fix and great library!
