### ISSUE TITLE
Hiding headings from the ToC

### ISSUE THREAD

**Issue by Buzzardo** [tscanlin/tocbot#74]
Hi,

In our documentation set, we hide some content based on a toggle that the reader can select. When that includes a heading, we'd like to hide the heading from the ToC, too. If we could do something like add a class (perhaps called "hideFromToC" to the heading when we want to hide it and remove the class when we want to show it, that'd do the trick. (We'd use the refresh function to redraw after hiding or showing).

Thanks.

**Comment by tscanlin** [comment]
That option actually already exists, see:
https://github.com/tscanlin/tocbot/blob/master/src/js/default-options.js#L9

**Comment by Buzzardo** [comment]
I'll give it a whirl. Thanks.
