### ISSUE TITLE
Limitation on number of nodes in TOC

### ISSUE THREAD

**Issue by dcp65** [tscanlin/tocbot#79]
I have a TOC that has 172 (!) sub-nodes under a top-level node (the document is an API reference generated from Swagger via swagger2markup).

Only 114 of the nodes are rendered by Tocbot, even though I can see all 172 list items in the generated HTML source.

Is this a known limitation?

**Comment by tscanlin** [comment]
Hmm, it’s probably because of the max height on the toc container. You can try overriding that to be a larger value.

**Comment by dcp65** [comment]
That was easy! Excellent. Thanks @tscanlin.
