### ISSUE TITLE
Undesired extra space after </html> tag

### ISSUE THREAD

**Issue by inwardmovement** [tscanlin/tocbot#80]
When the table of content is activated, an extra space is added after the closing </html> tag like so:

![image](https://user-images.githubusercontent.com/9438102/35994978-50d9aac2-0d12-11e8-8ee0-2cbbeb548427.png)

I guess it is to allow jumping to the last heading even if there is not enough space to do so but how can I prevent/control that? (I just copied the code from the documentation without adding modifications)

**Comment by inwardmovement** [comment]
Mh I don't know why but after working on the styling of the TOC the space is not there any more. Seems like an inconsistent behavior.

**Comment by tscanlin** [comment]
I don’t think it’s inconsistent, it’s by design so that you can scroll to all headings. This property on .content probably caused it ‘margin-bottom: 95vh’

**Comment by inwardmovement** [comment]
Ok but now there is no extra-space anymore so I can't scroll to all headings. But for me it's better like this.

**Comment by tscanlin** [comment]
Glad to hear
