### ISSUE TITLE
Seems not support non English title?

### ISSUE THREAD

**Issue by mashirozx** [tscanlin/tocbot#81]
It's unable to jump to a element with a Chinese (uft-8) id like `<a href="#第一章">第一章</a>` and `<h1 id="第一章">第一章<h1>`

You may see it [Here](https://2heng.xin/2017/09/19/pixiv/)

I guess it maybe href to id itself not support utf-8 characters, so am I able to change the id into something else? Like only a number as id instead of the original text?

**Comment by tscanlin** [comment]
Tocbot actually doesn't control heading ids, those come from your markdown parser. But you can just use regular <h2> tags with an id specified manually in this case. Otherwise you'd need to customize the markdown parser.

**Comment by mashirozx** [comment]
Yes, you are right  XD
I'm considering of adding the feature to covert all tags like `<h1 id="balabala">balabala<h1>' into '<hi id="balabala"><span id="num-1">balabala<span><h1>`
Is there anyway to make tocbot work with the `span` id?

**Comment by tscanlin** [comment]
You should be able to use the headings selector option to do that

**Comment by mashirozx** [comment]
@tscanlin It works, thanks you  😆

**Comment by vimcaw** [comment]
@mashirozx 怎么解决的？我也遇到这个问题了。把h1标签替换成其它标签？

**Comment by mashirozx** [comment]
@vimcaw 把 <h1 id="balabala">balabala<h1> 替换成 <hi id="balabala"><span id="num-1">balabala<span><h1>，tocbot初始化的时候把 h1 换成 h1 span就可以了

**Comment by mashirozx** [comment]
@vimcaw 是的

**Comment by vimcaw** [comment]
@tscanlin @mashirozx 

I have fixed this bug and commit a `pull request`.

In the `tocbot/src/js/scroll-smooth/index.js`
```js
var tgt = document.querySelector('[id="' + target.split('#').join('') + '"]')
```
- `tgt`: [object HTMLHeadingElement] target element
- `target`: [string] toc item, a.herf

When heading is nonASCII, a.herf will be encoded, but `id` attribute will be not encoded, it leads to not finding the tgt element by id.

For example, `WMI读取硬件信息` will encoded to `WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF`, but its `id` attribute is still `WMI读取硬件信息`, so `document.querySelector('[id="WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF"]')` can't find element, should be `document.querySelector('[id="WMI读取硬件信息"]')`.

After I add a decoding, it works on nonASCII heading.
```js
// DecodeURI for nonASCII hashes, they was encoded, but id was not encoded, it lead to not finding the tgt element by id.
var tgt = document.querySelector('[id="' + decodeURI(target).split('#').join('') + '"]')
```

**Comment by mashirozx** [comment]
@vimcaw

You may use this simple script to auto generat id name...

```js
var id = 1;
$(".entry-content").children("h1,h2,h3,h4,h5").each(function () {
    // entry-content is the main content container
    //var hyphenated = $(this).text().replace(/\s/g, '-');
    // Use this line if you like the original title as id
    var hyphenated = "toc-title-" + id;
    $(this).attr('id', hyphenated);
    id++;
});
```

**Comment by vimcaw** [comment]
@mashirozx 感谢你的帮助，但这个问题是他用的平滑滚动库没处理好的非ASCII字符的 bug，在源代码里加个URI解码就可以了，我已经修复了。
https://github.com/tscanlin/tocbot/pull/84

**Comment by mashirozx** [comment]
@vimcaw
 Yep, maybe yours will be more convenient 😆

**Comment by mashirozx** [comment]
@vimcaw
 Yep, maybe yours will be more convenient 😆

其实也不算是他的bug，是a标签的#跳转本身就不支持utf8 😂

**Comment by vimcaw** [comment]
`URL` 确实只能包含 `ASCII 码` ，但现代浏览器都会对URL中的 `非 ASCII 码` 进行自动编码，所以其实在`a 标签的链接`和`浏览器的地址栏`都可以支持中文，但 `id` 属性支持非 `ASCII` 码，所以没有进行编码。
他那里是直接通过 `a` 标签的链接去掉 # 号来当作 h1 - h5 标签的 `id`，那样 a 标签的链接已经编码了（比如：`WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF`），而 h1 - h5 标签的 id 还是中文（比如：`WMI读取硬件信息`），所以通过
```js
$("#WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF ") 
```
找不到对应的 
```html
<h1 id="WMI读取硬件信息">WMI读取硬件信息<h1> 
```
元素。
