### ISSUE TITLE
[Feature Request] Add Active Link Class to li element instead of a element

### ISSUE THREAD

**Issue by vimcaw** [tscanlin/tocbot#83]
I want to change the `li` element style of active link, but tocbot add Active Link Class to the `a` element, and CSS selector can't select the special parent in according to its child element with the special status.
Can you add an option to choose if Add Active Link Class to `li` element?

**Comment by mashirozx** [comment]
可以使用jQuery的children方法遍历li内的元素，see: <https://api.jquery.com/children/>
如果是active的元素那么直接设置 `.is-active-link`的属性就可以了呀

**Comment by vimcaw** [comment]
@mashirozx `.is-active-link`的类名是挂在`a`标签上的，而`li`标签是`a`标签的父元素。
```html
<li class="toc-list-item">
    <a href="#改变图层顺序" class="toc-link node-name--H2  is-active-link">改变图层顺序</a>
</li>
```
css貌似不能选中子元素的类名为`.is-active-link`的父元素。

**Comment by mashirozx** [comment]
@vimcaw 是不是你没改对？我这里能改的呀 <https://2heng.xin/2017/09/19/pixiv/>
![image](https://user-images.githubusercontent.com/16148054/36074640-ee90722e-0f7d-11e8-96e9-3b72873c11ae.png)

**Comment by vimcaw** [comment]
你这样改的还是`a`标签的样式，原作者就是用`::before`伪元素把`a`标签的`border-left`设置到父元素的最左边，看上去就像是`li`元素的样式一样。
比如要想改`active`那行的字体颜色，就只能修改`a`标签的颜色，而前面的数字的颜色还是改不了。

2018-02-11 22:50 GMT+08:00 Mashiro <notifications@github.com>:

**Comment by tscanlin** [comment]
Is this still needed? What is the styling that you are trying to accomplish?

**Comment by vimcaw** [comment]
@tscanlin yeah, I want to change `color` & `background` for `li` element of active link parent.

**Comment by tscanlin** [comment]
@vimcaw couldn't you change the link to have the styling:
```
.toc-link {
    width: 100%;
    display: inline-block;
}
```
Then it should have the same bounding box as the parent li tag and you could have a background going full width. Does that help accomplish the styling you want to achieve? Otherwise can you post a code example of the styling issue you are having?

**Comment by vimcaw** [comment]
For example, I create a page: https://vimcaw.github.io/code-preview/toc-bot/index.html

![image](https://user-images.githubusercontent.com/21964227/36489253-865ba1fc-1760-11e8-83ae-37aef829a3d6.png)

Because `is-active-link` className was added to `a` element instead of `li` element, the color of the `active-link` left number can't be changed.

**Comment by tscanlin** [comment]
Can you checkout this branch to see if it will help you accomplish your goal? https://github.com/tscanlin/tocbot/pull/88

**Comment by vimcaw** [comment]
@tscanlin 
Yeah, this is what I want. wonderful solution! 👍 Thank you very much!
