### ISSUE TITLE
Remove div when there are no headings

### ISSUE THREAD

**Issue by SPQRInc** [tscanlin/tocbot#85]
Hello,

is it possible to easily remove the toc-div if there's no matching heading in the DOM?

**Comment by tscanlin** [comment]
You could probably use the empty pseudo selector in css to accomplish this:
https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

**Comment by SPQRInc** [comment]
Hi Tim,

thanks for your reply. Well, I'm not a genius in CSS, but unfortunately this example does not work:

```
.toc:empty {
     display: none;
}
```

I guess it's because it is not empty ;) 

```
<div class="toc uk-panel uk-panel-box uk-visible-large sticky-toc" style="margin: 0px;"><ol class="uk-nav uk-nav-side "></ol></div>
```

It still contains an ordered list. Maybe this is the problem?

**Comment by tscanlin** [comment]
Yeah, but the ordered list is empty so you could just target that, right? Although maybe the toc container has width set on it now which could just be moved to the list.

**Comment by SPQRInc** [comment]
Hi,

yes, the `ol` can be targeted - but the parent `div` is still there and can not be hidden, because :empty can not be used on parent elements (CSS does not know `parent`).

So I think the best way would be if the tocbot does not return an `ol` if there are no elements in it.

**Comment by tscanlin** [comment]
Let me look into adding that feature. I’d also accept a pull request if you have the time.

**Comment by SPQRInc** [comment]
I'd love to help you out - but my JS skills not that good :-/

**Comment by tscanlin** [comment]
No worries. I'm looking into fixing it but not able to reproduce this issue locally on the latest version. But I think older versions may have had this issue. What version of tocbot are you using?

**Comment by SPQRInc** [comment]
I installed tocbot via `npm`.

It's version `4.1.1`.

```
Tim Scanlin',
  bugs: { url: 'https://github.com/tscanlin/tocbot/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '4.1.1',
```

**Comment by tscanlin** [comment]
I think I see the issue. It appears to only happen with refresh and not on first page load. I have a fix for it here:
https://github.com/tscanlin/tocbot/pull/86/files#diff-8666d86add09b3aebb713bcaa8b0fb43R57

Can you see if that fixes the issue?

**Comment by SPQRInc** [comment]
Yes - that fixes the issue.
Would be great if that could be bundled to a new release, as I included tocbot to a (also MIT-licensed) extension for Pagekit CMS and the users could get an update if you create a new release :)

Thank you very much for your work!

**Comment by tscanlin** [comment]
Great to hear. I published `4.2.0` with the fix.

That's awesome that you're able to use it in another open source project, very cool!

Would you mind if I linked to:
https://github.com/SPQRInc/pagekit-toc
In the examples section of the tocbot readme?

No worries if you're not interested.

**Comment by SPQRInc** [comment]
Of course that‘s okay. I‘d be happy about that :)

- https://github.com/SPQRInc/pagekit-toc
or
- https://spqr.wtf/projects/toc

I will update the extension tomorrow (it’s already 11pm in Germany and I have to wake up again in 5 hours :-/ ). I think the users will be very happy about that bugfix :)

Thank you very much :)

**Comment by tscanlin** [comment]
Great to hear. I've updated the Readme with the second link :)

Take care!
