### ISSUE TITLE
Adding tocbot lets href='#' jump to page header

### ISSUE THREAD

**Issue by SPQRInc** [tscanlin/tocbot#87]
Hi everybody,

I just mentioned the following:

If I include `app/assets/tocbot/tocbot.js` all links that are leading to `#` are bringing me back to the pagestart. If I don't include `app/assets/tocbot/tocbot.js` this is not the case.

Example: Visit https://reptilien.blog/blog/2018/02/futtertierzucht and click on `Antworten` (German for "Answer") and the link points to the top of the page.

Do the same thing [here](https://spqr.wtf/blog/2018/01/08/spqr-wordpressimport-released#comments) and it does not jump to the page's top.

I'm really not good in JS - but this shouldn't be the case, right?

**Comment by tscanlin** [comment]
This is actually default browser behavior. Anyway, you can use “#!” For the href to keep it from jumping to the top.

**Comment by SPQRInc** [comment]
Unfortunately I can not edit the href - they are set by the CMS. But: Why does it not jump to the top when I disable tocbot?

**Comment by tscanlin** [comment]
Hmm, maybe the JS is interfering. Can you try `4.2.1`

**Comment by SPQRInc** [comment]
It works with ´4.2.1´ - thank you very much!
