### ISSUE TITLE
Tocbot has problems working with VueJS

### ISSUE THREAD

**Issue by SPQRInc** [tscanlin/tocbot#89]
Hi Tim,

me again :D 

If Vuejs is used with tocbot, tocbot uses `{{ my-string }}` as output:

<img width="1044" alt="bildschirmfoto 2018-02-22 um 15 10 00" src="https://user-images.githubusercontent.com/23051150/36542968-aba72cd8-17e2-11e8-82ff-d43aeb5efaf7.png">
<img width="799" alt="bildschirmfoto 2018-02-22 um 15 10 23" src="https://user-images.githubusercontent.com/23051150/36542969-abc6b530-17e2-11e8-80a9-9ee54f0713da.png">
<img width="672" alt="bildschirmfoto 2018-02-22 um 15 10 43" src="https://user-images.githubusercontent.com/23051150/36542971-abee80e2-17e2-11e8-9ccc-4b82643aa2fe.png">

Is it possible to get tocbot working with Vue?

**Comment by tscanlin** [comment]
That is probably because you are initializing Tocbot before vue. Make sure vue is initialized first.

**Comment by SPQRInc** [comment]
Hm, I'm not sure.

I am doing this:

```
$(function() { tocbot.init({ $paramstring }); });
```

Should be executed after DOM is ready, right?

**Comment by SPQRInc** [comment]
Hm, I just found out that it's possible to solve this, if I load the `tocbot.init` async.

But: I need to use PHP to insert the param string, as it's configurable in the backend. I thought about using the CMS' events to create a little JS file that contains the param once the settings are saved, but as the CMS also supports widgets I would need to create a lot of unique init files. Does not seem to be the best way.

As I'm not experienced enough with JS: Is there any other possibility?

**Comment by tscanlin** [comment]
That will load once the Dom is ready, but doesn’t necessarily mean vue has loaded / compiled. Have you tried changing the ordering of scripts? I’d imagine it’s just the way they are being loaded. An example would help.

As a last resort you could wrap Tocbot init in a set timeout.

**Comment by SPQRInc** [comment]
Unfortunately changing the ordering is not possible in the cms :-/

I will try to give an example. Could you link an example of a „set timeout“?

**Comment by SPQRInc** [comment]
I created a little demo on https://spqr.wtf/demo/ .

**Comment by tscanlin** [comment]
```
setTimeout(function () {
  tocbot.init()
})
```

**Comment by SPQRInc** [comment]
Solved it using

```
window.onload = function () { tocbot.init({ ... }); }
```

Thanks for your help :)
