### ISSUE TITLE
(node:41536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: name (tocbot)

### ISSUE THREAD

**Issue by vimcaw** [tscanlin/tocbot#90]
I use `npm` to install `tocbot`, import it and init it.
I don't use the tool like `webpack` or `gulp`.
```js
import tocbot from 'tocbot'

tocbot.init({
    // Where to render the table of contents.
    tocSelector: '.sidebar',
    // Where to grab the headings to build the table of contents.
    contentSelector: 'article',
    // Which headings to grab inside of the contentSelector element.
    headingSelector: 'h1, h2, h3',
    onClick: function () {
        if (shade.style.display === 'block') {
            switchSidebar();
        }
    }
});
```
But when I run, console display:
```console
(node:41536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: name (tocbot)
```

**Comment by tscanlin** [comment]
Can you link me to an example? Maybe its not being imported properly?

**Comment by vimcaw** [comment]
This project is powered by `hexo`, and this error doesn't recurrent in another environment.
Maybe I wrongly use it.
Must it need the tool like `webpack` or `gulp`?

**Comment by tscanlin** [comment]
I believe hexo on its own doesn’t handle bundling frontend assets as it’s a tool to generate static sites. 

Do you options are: add webpack to hexo to support bundling / importing assets. Use something like gatsby which does use webpack, or just include the script on the page like so:

<script src="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.1.1/tocbot.min.js"></script>

Hope that helps!

**Comment by vimcaw** [comment]
You are right, thanks.
