### ISSUE TITLE
IE11 JavaScript error

### ISSUE THREAD

**Issue by TomFranssen** [tscanlin/tocbot#93]
In IE11 I get the following error:
`Object doesn't support property or method 'assign'`
I see this has been added 21 febuary in this commit: https://github.com/tscanlin/tocbot/commit/19af3464ada501aa843bc911a986c9cc7bc48213
It looks like IE11 needs a polyfill for Object.assign to work: https://www.npmjs.com/package/object-assign

**Comment by tscanlin** [comment]
Thanks for reporting this @TomFranssen https://github.com/tscanlin/tocbot/pull/94 should fix it.

**Comment by tscanlin** [comment]
`4.3.2` should fix it, reply if you still have issues.

Thanks for using tocbot!
