### ISSUE TITLE
The first click can link to the right title , while the second time will not .

### ISSUE THREAD

**Issue by mrmeisen** [tscanlin/tocbot#95]
Hello:
My Id looks like this: 
```
<h2 id="aXzcHpMr">技术栈</h2>
```
![gif](https://user-images.githubusercontent.com/23736683/40178329-c0641ab4-5a13-11e8-9e50-69452978021b.gif)

**Comment by tscanlin** [comment]
Can you link me to an example? I can’t help troubleshoot without more information.

**Comment by mrmeisen** [comment]
I think i find the problem. I use tocbot with reactjs. I click the link ,it will recall render(). My render function contains tocbot.init. so it will generate new hrefs. That is why my website function wrong. But I did not find  solution yet.
```js
 render() {
        tocbot.init({...tocOption(),  headingsOffset: -window.innerHeight});
        console.log('render');
        return (
          <div className='bar-toc'>
                    </div>
        )
}
```

**Comment by tscanlin** [comment]
You should be able to just initialize in ‘componentDidMount’ and it should help take care of this issue. See if that helps.
