### ISSUE TITLE
headingSelector setting exception

### ISSUE THREAD

**Issue by Honghe** [tscanlin/tocbot#97]
## Environment
* tocbot: 4.3.2
* Chrome v66

## Phenomena
* set `headingSelector`  as follow, but still only 2 level headers displayed.
```
  tocbot.init({
    // Where to render the table of contents.
    tocSelector: '#contents-list',
    // Where to grab the headings to build the table of contents.
    contentSelector: '.post-content',
    // Which headings to grab inside of the contentSelector element.
    headingSelector: 'h1, h2, h3',
  });
```
![image](https://user-images.githubusercontent.com/1092722/40885597-f1ede826-675b-11e8-836e-bde72bddd2fa.png)

* if set  `headingSelector: 'h1'` , it can display only level 1 header, it is normal.

Can I ask how to debug it?

**Comment by tscanlin** [comment]
Sorry to hear this issue is happening. Are you loading any of the content async? Also, if you add other h3 headings do they show up? Any console errors?

Also, what if you change to `headingSelector: 'h1, h2, h3',`?

**Comment by Honghe** [comment]
It auto collapsed. After setting `collapseDepth: 6`, it is OK now.

**Comment by tscanlin** [comment]
Good to hear that fixed it. Are you including all of the css?

**Comment by tscanlin** [comment]
or maybe there isn't enough content between the headings for that heading to not be auto hidden?
