### ISSUE TITLE
How to unwrap header item when it is too long

### ISSUE THREAD

**Issue by Honghe** [tscanlin/tocbot#98]
How to unwrap the item when it is too long?
Such as, unwrap the long item, but when the mouse hover on the item, it can prompt the whole item content.
Thanks!

![image](https://user-images.githubusercontent.com/1092722/40899090-b0d2ff88-67f7-11e8-8ca6-e14edc9c3d5a.png)

**Comment by Honghe** [comment]
下面可以给大家粗略地讲讲这些模型：

（1）CPM的算法思想（单人姿态估计）

CPM的模型采用的大卷积核来获得大的感受野，这对于推断被遮挡的关节是很有效的。网络结构如下

整个算法的流程是：

1）首先对图像的所有出现的人进行回归，回归各个人的关节的点

2）然后根据center map来去除掉对其他人的响应

3）最后通过重复地对预测出来的heatmap进行refine得到最终的结果

在进行refine的时候，需要引入中间层的loss，从而保证较深的网络仍然可以训练下去，不至于梯度弥散或者爆炸。

这种思路很好，通过coarse to fine来逐渐提升回归的准确度。

（2）realtime multi-person pose estimation的算法思想（多人姿态估计）

该算法其实是基于CPM来构造的，所以计算量也很可观这就是为什么在上述回答中有些

**Comment by tscanlin** [comment]
You can use CSS for that, see: https://stackoverflow.com/questions/34833815/showing-truncated-text-on-hover-using-css-ellipsis-overlaps-text-below-it
